// Copyright 2020 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

/**
* WARNING: do not modify this file by hand!
* it was automatically generated by the bridge generator
* if you made changes to the source code and need to update this file, run:
*  npm run generate-bridge-file front_end/ui/components/DataGridController.ts
*/

import './DataGridController.js';
/**
* @typedef {{
* columns:!Array.<!Column>,
* rows:!Array.<!Row>,
* filterText:(string|undefined),
* }}
*/
// @ts-ignore we export this for Closure not TS
export let DataGridControllerData;
/**
* @typedef {{
* id:string,
* title:string,
* sortable:(boolean|undefined),
* widthWeighting:number,
* hidden:(boolean|undefined),
* }}
*/
// @ts-ignore we export this for Closure not TS
export let Column;
/**
* @typedef {{
* cells:!Array.<!Cell>,
* hidden:(boolean|undefined),
* }}
*/
// @ts-ignore we export this for Closure not TS
export let Row;
/**
* @typedef {{
* columnId:string,
* value:*,
* renderer:(!function(*):*|undefined),
* }}
*/
// @ts-ignore we export this for Closure not TS
export let Cell;
// eslint-disable-next-line no-unused-vars
export class DataGridControllerClosureInterface extends HTMLElement {
  /**
  * @return {!DataGridControllerData}
  */
  get data() {
    throw new Error('Not implemented in _bridge.js');
  }
  /**
  * @param {!DataGridControllerData} data
  */
  set data(data) {
  }
}
/**
* @return {!DataGridControllerClosureInterface}
*/
export function createDataGridController() {
  return /** @type {!DataGridControllerClosureInterface} */ (document.createElement('devtools-data-grid-controller'));
}
