// Copyright 2020 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

/**
* WARNING: do not modify this file by hand!
* it was automatically generated by the bridge generator
* if you made changes to the source code and need to update this file, run:
*  npm run generate-bridge-file front_end/ui/components/DataGrid.ts
*/

import './DataGrid.js';
/**
* @typedef {{
* id:string,
* title:string,
* sortable:boolean,
* width:(number|undefined),
* }}
*/
// @ts-ignore we export this for Closure not TS
export let Column;
/**
* @typedef {{
* }}
*/
// @ts-ignore we export this for Closure not TS
export let Row;
// eslint-disable-next-line no-unused-vars
export class DataGridClosureInterface extends HTMLElement {
  /**
  * @param {{columns: !Array.<!Column>, rows: !Array.<!Row>}} data
  */
  set data(data) {
  }
}
/**
* @return {!DataGridClosureInterface}
*/
export function createDataGrid() {
  return /** @type {!DataGridClosureInterface} */ (document.createElement('devtools-data-grid'));
}
