// Copyright 2020 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

/**
* WARNING: do not modify this file by hand!
* it was automatically generated by the bridge generator
* if you made changes to the source code and need to update this file, run:
*  npm run generate-bridge-file front_end/linear_memory_inspector/LinearMemoryViewer.ts
*/

import './LinearMemoryViewer.js';
/**
* @typedef {{
* memory:!Uint8Array,
* address:number,
* memoryOffset:number,
* }}
*/
// @ts-ignore we export this for Closure not TS
export let LinearMemoryViewerData;
// eslint-disable-next-line no-unused-vars
export class LinearMemoryViewerClosureInterface extends HTMLElement {
  /**
  * @param {!LinearMemoryViewerData} data
  */
  set data(data) {
  }
}
/**
* @return {!LinearMemoryViewerClosureInterface}
*/
export function createLinearMemoryViewer() {
  return /** @type {!LinearMemoryViewerClosureInterface} */ (
      document.createElement('devtools-linear-memory-inspector-viewer'));
}
