// Copyright 2020 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

/**
* WARNING: do not modify this file by hand!
* it was automatically generated by the bridge generator
* if you made changes to the source code and need to update this file, run:
*  npm run generate-bridge-file front_end/timeline/WebVitalsTimeline.ts
*/

import './WebVitalsTimeline.js';
/**
* @typedef {{
* startTime:number,
* duration:number,
* fcps:Array.<number>,
* lcps:Array.<number>,
* layoutShifts:Array.<number>,
* longTasks:Array.<!WebVitalsTimelineTask>,
* }}
*/
// @ts-ignore we export this for Closure not TS
export let WebVitalsTimelineData;
/**
* @typedef {{
* start:number,
* duration:number,
* }}
*/
// @ts-ignore we export this for Closure not TS
export let WebVitalsTimelineTask;
// eslint-disable-next-line no-unused-vars
export class WebVitalsTimelineClosureInterface extends HTMLElement {
  /**
  * @param {!WebVitalsTimelineData} data
  */
  set data(data) {
  }
}
/**
* @return {!WebVitalsTimelineClosureInterface}
*/
export function createWebVitalsTimeline() {
  return /** @type {!WebVitalsTimelineClosureInterface} */ (document.createElement('devtools-timeline-webvitals'));
}
