// Copyright 2020 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

/**
* WARNING: do not modify this file by hand!
* it was automatically generated by the bridge generator
* if you made changes to the source code and need to update this file, run:
*  npm run generate-bridge-file front_end/elements/CSSAngle.ts
*/

import './CSSAngle.js';
/**
* @enum {string}
*/
// @ts-ignore we export this for Closure not TS
export let AngleUnit = {
  Deg: 'deg',
  Grad: 'grad',
  Rad: 'rad',
  Turn: 'turn',
};
// eslint-disable-next-line no-unused-vars
export class CSSAngleClosureInterface extends HTMLElement {
  /**
  * @param {string} text
  * @return {void}
  */
  setText(text) {
  }
  /**
  * @return {void}
  */
  popover() {
  }
  /**
  * @return {void}
  */
  minify() {
  }
  /**
  * @param {{value: number, unit: !AngleUnit}} data
  */
  set data(data) {
  }
}
/**
* @return {!CSSAngleClosureInterface}
*/
export function createCSSAngle() {
  return /** @type {!CSSAngleClosureInterface} */ (document.createElement('devtools-css-angle'));
}
