// Copyright 2020 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

/**
* WARNING: do not modify this file by hand!
* it was automatically generated by the bridge generator
* if you made changes to the source code and need to update this file, run:
*  npm run generate-bridge-file front_end/elements/ElementsStyleSidebar.ts
*/

import './ElementsStyleSidebar.js';
/**
* @typedef {{
* indentation:number,
* selectors:!Array.<!StyleSelector>,
* rules:!Array.<!StyleRule>,
* }}
*/
// @ts-ignore we export this for Closure not TS
export let StyleData;
/**
* @typedef {{
* selector:string,
* matches:boolean,
* }}
*/
// @ts-ignore we export this for Closure not TS
export let StyleSelector;
/**
* @typedef {{
* name:string,
* value:string,
* enabled:boolean,
* subRules:(!Array.<!StyleRule>|undefined),
* }}
*/
// @ts-ignore we export this for Closure not TS
export let StyleRule;
// eslint-disable-next-line no-unused-vars
export class ElementsStyleSidebarClosureInterface extends HTMLElement {
  /**
  * @return {!StyleData}
  */
  get data() {
    throw new Error('Not implemented in _bridge.js');
  }
  /**
  * @param {!StyleData} data
  */
  set data(data) {
  }
}
/**
* @return {!ElementsStyleSidebarClosureInterface}
*/
export function createElementsStyleSidebar() {
  return /** @type {!ElementsStyleSidebarClosureInterface} */ (document.createElement('elements-style-sidebar'));
}
