// Copyright 2020 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

/**
* WARNING: do not modify this file by hand!
* it was automatically generated by the bridge generator
* if you made changes to the source code and need to update this file, run:
*  npm run generate-bridge-file front_end/elements/IconComponent.ts
*/

import './IconComponent.js';
/**
* @typedef {IconWithPath|IconWithName}
*/
// @ts-ignore we export this for Closure not TS
export let IconComponentData;
/**
* @typedef {{
* iconPath:string,
* color:string,
* width:(string|undefined),
* height:(string|undefined),
* }}
*/
// @ts-ignore we export this for Closure not TS
export let IconWithPath;
/**
* @typedef {{
* iconName:string,
* color:string,
* width:(string|undefined),
* height:(string|undefined),
* }}
*/
// @ts-ignore we export this for Closure not TS
export let IconWithName;
// eslint-disable-next-line no-unused-vars
export class IconComponentClosureInterface extends HTMLElement {
  /**
  * @return {!IconComponentData}
  */
  get data() {
    throw new Error('Not implemented in _bridge.js');
  }
  /**
  * @param {!IconComponentData} data
  */
  set data(data) {
  }
}
/**
* @return {!IconComponentClosureInterface}
*/
export function createIconComponent() {
  return /** @type {!IconComponentClosureInterface} */ (document.createElement('devtools-icon-component'));
}
