// Copyright 2020 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

/**
* WARNING: do not modify this file by hand!
* it was automatically generated by the bridge generator
* if you made changes to the source code and need to update this file, run:
*  npm run generate-bridge-file front_end/elements/LayoutPane.ts
*/

import './LayoutPane.js';
/**
* @typedef {*}
*/
// @ts-ignore we export this for Closure not TS
export let Setting;
// eslint-disable-next-line no-unused-vars
export class LayoutPaneClosureInterface extends HTMLElement {
  /**
  * @param {{settings: !Array.<!Setting>, theme: string}} data
  */
  set data(data) {
  }
}
/**
* @return {!LayoutPaneClosureInterface}
*/
export function createLayoutPane() {
  return /** @type {!LayoutPaneClosureInterface} */ (document.createElement('devtools-layout-pane'));
}
