// Generated from scripts/javascript_natives/index.js
export const NativeFunctions = [
  {'name': 'find', 'signatures': [['predicate', '?thisArg']]},
  {'name': 'findIndex', 'signatures': [['predicate', '?thisArg']]},
  {'name': 'fill', 'signatures': [['value', '?start', '?end']]},
  {'name': 'copyWithin', 'signatures': [['target', 'start', '?end']]},
  {
    'name': 'from',
    'signatures': [['arrayLike', '?mapfn', '?thisArg'], ['iterable', '?mapfn', '?thisArg']],
    'static': true,
    'receiver': 'Array'
  },
  {'name': 'from', 'signatures': [['arrayLike', '?mapfn', '?thisArg']], 'static': true, 'receiver': 'Int8Array'},
  {'name': 'from', 'signatures': [['arrayLike', '?mapfn', '?thisArg']], 'static': true, 'receiver': 'Uint8Array'},
  {
    'name': 'from',
    'signatures': [['arrayLike', '?mapfn', '?thisArg']],
    'static': true,
    'receiver': 'Uint8ClampedArray'
  },
  {'name': 'from', 'signatures': [['arrayLike', '?mapfn', '?thisArg']], 'static': true, 'receiver': 'Int16Array'},
  {'name': 'from', 'signatures': [['arrayLike', '?mapfn', '?thisArg']], 'static': true, 'receiver': 'Uint16Array'},
  {'name': 'from', 'signatures': [['arrayLike', '?mapfn', '?thisArg']], 'static': true, 'receiver': 'Int32Array'},
  {'name': 'from', 'signatures': [['arrayLike', '?mapfn', '?thisArg']], 'static': true, 'receiver': 'Uint32Array'},
  {'name': 'from', 'signatures': [['arrayLike', '?mapfn', '?thisArg']], 'static': true, 'receiver': 'Float32Array'},
  {'name': 'from', 'signatures': [['arrayLike', '?mapfn', '?thisArg']], 'static': true, 'receiver': 'Float64Array'},
  {'name': 'of', 'signatures': [['...items']]},
  {'name': 'clz32', 'signatures': [['x']]},
  {'name': 'imul', 'signatures': [['x', 'y']]},
  {'name': 'sign', 'signatures': [['x']]},
  {'name': 'log10', 'signatures': [['x']]},
  {'name': 'log2', 'signatures': [['x']]},
  {'name': 'log1p', 'signatures': [['x']]},
  {'name': 'expm1', 'signatures': [['x']]},
  {'name': 'cosh', 'signatures': [['x']]},
  {'name': 'sinh', 'signatures': [['x']]},
  {'name': 'tanh', 'signatures': [['x']]},
  {'name': 'acosh', 'signatures': [['x']]},
  {'name': 'asinh', 'signatures': [['x']]},
  {'name': 'atanh', 'signatures': [['x']]},
  {'name': 'hypot', 'signatures': [['...values']]},
  {'name': 'trunc', 'signatures': [['x']]},
  {'name': 'fround', 'signatures': [['x']]},
  {'name': 'cbrt', 'signatures': [['x']]},
  {'name': 'isFinite', 'signatures': [['number']]},
  {'name': 'isInteger', 'signatures': [['number']]},
  {'name': 'isNaN', 'signatures': [['number']]},
  {'name': 'isSafeInteger', 'signatures': [['number']]},
  {'name': 'parseFloat', 'signatures': [['string']]},
  {'name': 'parseInt', 'signatures': [['string', '?radix']], 'static': true, 'receiver': 'Number'},
  {'name': 'parseInt', 'signatures': [['s', '?radix']], 'receiver': 'Window'},
  {
    'name': 'assign',
    'signatures': [['target', 'source'], ['target', '...sources'], ['target', 'source1', 'source2', '?source3']]
  },
  {'name': 'getOwnPropertySymbols', 'signatures': [['o']]},
  {'name': 'is', 'signatures': [['value1', 'value2']]},
  {'name': 'setPrototypeOf', 'signatures': [['o', 'proto']], 'static': true, 'receiver': 'Object'},
  {'name': 'setPrototypeOf', 'signatures': [['target', 'v']], 'receiver': 'ProxyHandler'},
  {'name': 'codePointAt', 'signatures': [['pos']]},
  {'name': 'includes', 'signatures': [['searchString', '?position']], 'receiver': 'String'},
  {'name': 'includes', 'signatures': [['searchElement', '?fromIndex']], 'receiver': 'Array'},
  {'name': 'includes', 'signatures': [['searchElement', '?fromIndex']], 'receiver': 'ReadonlyArray'},
  {'name': 'includes', 'signatures': [['searchElement', '?fromIndex']], 'receiver': 'Int8Array'},
  {'name': 'includes', 'signatures': [['searchElement', '?fromIndex']], 'receiver': 'Uint8Array'},
  {'name': 'includes', 'signatures': [['searchElement', '?fromIndex']], 'receiver': 'Uint8ClampedArray'},
  {'name': 'includes', 'signatures': [['searchElement', '?fromIndex']], 'receiver': 'Int16Array'},
  {'name': 'includes', 'signatures': [['searchElement', '?fromIndex']], 'receiver': 'Uint16Array'},
  {'name': 'includes', 'signatures': [['searchElement', '?fromIndex']], 'receiver': 'Int32Array'},
  {'name': 'includes', 'signatures': [['searchElement', '?fromIndex']], 'receiver': 'Uint32Array'},
  {'name': 'includes', 'signatures': [['searchElement', '?fromIndex']], 'receiver': 'Float32Array'},
  {'name': 'includes', 'signatures': [['searchElement', '?fromIndex']], 'receiver': 'Float64Array'},
  {'name': 'endsWith', 'signatures': [['searchString', '?endPosition']]},
  {'name': 'normalize', 'signatures': [['?form']]},
  {'name': 'repeat', 'signatures': [['count']]},
  {'name': 'startsWith', 'signatures': [['searchString', '?position']]},
  {'name': 'anchor', 'signatures': [['name']]},
  {'name': 'fontcolor', 'signatures': [['color']]},
  {'name': 'fontsize', 'signatures': [['size']]},
  {'name': 'link', 'signatures': [['url']]},
  {'name': 'sub', 'signatures': [['typedArray', 'index', 'value']], 'receiver': 'Atomics'},
  {'name': 'fromCodePoint', 'signatures': [['...codePoints']]},
  {'name': 'raw', 'signatures': [['template', '...substitutions']]},
  {'name': 'delete', 'signatures': [['key']], 'receiver': 'Map'},
  {'name': 'delete', 'signatures': [['key']], 'receiver': 'WeakMap'},
  {'name': 'delete', 'signatures': [['value']], 'receiver': 'Set'},
  {'name': 'delete', 'signatures': [['value']], 'receiver': 'WeakSet'},
  {'name': 'forEach', 'signatures': [['callbackfn', '?thisArg']]},
  {'name': 'get', 'signatures': [['key']], 'receiver': 'Map'},
  {'name': 'get', 'signatures': [['key']], 'receiver': 'ReadonlyMap'},
  {'name': 'get', 'signatures': [['key']], 'receiver': 'WeakMap'},
  {'name': 'get', 'signatures': [['target', 'p', 'receiver']], 'receiver': 'ProxyHandler'},
  {'name': 'has', 'signatures': [['key']], 'receiver': 'Map'},
  {'name': 'has', 'signatures': [['key']], 'receiver': 'ReadonlyMap'},
  {'name': 'has', 'signatures': [['key']], 'receiver': 'WeakMap'},
  {'name': 'has', 'signatures': [['value']], 'receiver': 'Set'},
  {'name': 'has', 'signatures': [['value']], 'receiver': 'ReadonlySet'},
  {'name': 'has', 'signatures': [['value']], 'receiver': 'WeakSet'},
  {'name': 'has', 'signatures': [['target', 'p']], 'receiver': 'ProxyHandler'},
  {'name': 'set', 'signatures': [['key', 'value']], 'receiver': 'Map'},
  {'name': 'set', 'signatures': [['key', 'value']], 'receiver': 'WeakMap'},
  {'name': 'set', 'signatures': [['target', 'p', 'value', 'receiver']], 'receiver': 'ProxyHandler'},
  {'name': 'set', 'signatures': [['v']], 'receiver': 'PropertyDescriptor'},
  {'name': 'set', 'signatures': [['array', '?offset']], 'receiver': 'Int8Array'},
  {'name': 'set', 'signatures': [['array', '?offset']], 'receiver': 'Uint8Array'},
  {'name': 'set', 'signatures': [['array', '?offset']], 'receiver': 'Uint8ClampedArray'},
  {'name': 'set', 'signatures': [['array', '?offset']], 'receiver': 'Int16Array'},
  {'name': 'set', 'signatures': [['array', '?offset']], 'receiver': 'Uint16Array'},
  {'name': 'set', 'signatures': [['array', '?offset']], 'receiver': 'Int32Array'},
  {'name': 'set', 'signatures': [['array', '?offset']], 'receiver': 'Uint32Array'},
  {'name': 'set', 'signatures': [['array', '?offset']], 'receiver': 'Float32Array'},
  {'name': 'set', 'signatures': [['array', '?offset']], 'receiver': 'Float64Array'},
  {'name': 'add', 'signatures': [['value']], 'receiver': 'Set'},
  {'name': 'add', 'signatures': [['value']], 'receiver': 'WeakSet'},
  {'name': 'add', 'signatures': [['typedArray', 'index', 'value']], 'receiver': 'Atomics'},
  {'name': 'all', 'signatures': [['values']]},
  {'name': 'race', 'signatures': [['values']]},
  {'name': 'reject', 'signatures': [['?reason']]},
  {'name': 'resolve', 'signatures': [['?value']]},
  {'name': 'for', 'signatures': [['key']]},
  {'name': 'keyFor', 'signatures': [['sym']]},
  {'name': 'next', 'signatures': [['?value']]},
  {'name': 'return', 'signatures': [['?value']]},
  {'name': 'throw', 'signatures': [['?e']]},
  {'name': 'entries', 'signatures': [['o']], 'static': true, 'receiver': 'Object'},
  {'name': 'keys', 'signatures': [['o']], 'static': true, 'receiver': 'Object'},
  {'name': 'values', 'signatures': [['o']], 'static': true, 'receiver': 'Object'},
  {'name': 'getPrototypeOf', 'signatures': [['target']], 'receiver': 'ProxyHandler'},
  {'name': 'getPrototypeOf', 'signatures': [['o']], 'static': true, 'receiver': 'Object'},
  {'name': 'isExtensible', 'signatures': [['target']], 'receiver': 'ProxyHandler'},
  {'name': 'isExtensible', 'signatures': [['o']], 'static': true, 'receiver': 'Object'},
  {'name': 'preventExtensions', 'signatures': [['target']], 'receiver': 'ProxyHandler'},
  {'name': 'preventExtensions', 'signatures': [['o']], 'static': true, 'receiver': 'Object'},
  {'name': 'getOwnPropertyDescriptor', 'signatures': [['target', 'p']], 'receiver': 'ProxyHandler'},
  {'name': 'getOwnPropertyDescriptor', 'signatures': [['o', 'p']], 'static': true, 'receiver': 'Object'},
  {'name': 'deleteProperty', 'signatures': [['target', 'p']]},
  {'name': 'defineProperty', 'signatures': [['target', 'p', 'attributes']], 'receiver': 'ProxyHandler'},
  {'name': 'defineProperty', 'signatures': [['o', 'p', 'attributes']], 'static': true, 'receiver': 'Object'},
  {'name': 'enumerate', 'signatures': [['target']]},
  {'name': 'ownKeys', 'signatures': [['target']]},
  {'name': 'apply', 'signatures': [['target', 'thisArg', '?argArray']], 'receiver': 'ProxyHandler'},
  {'name': 'apply', 'signatures': [['thisArg', '?argArray']], 'receiver': 'Function'},
  {'name': 'construct', 'signatures': [['target', 'argArray', '?newTarget']]},
  {'name': 'revocable', 'signatures': [['target', 'handler']]},
  {'name': 'match', 'signatures': [['matcher'], ['regexp']]},
  {'name': 'replace', 'signatures': [['searchValue', 'replaceValue'], ['searchValue', 'replacer']]},
  {'name': 'search', 'signatures': [['searcher'], ['regexp']]},
  {'name': 'split', 'signatures': [['splitter', '?limit'], ['separator', '?limit']]},
  {'name': 'eval', 'signatures': [['x']]},
  {'name': 'decodeURI', 'signatures': [['encodedURI']]},
  {'name': 'decodeURIComponent', 'signatures': [['encodedURIComponent']]},
  {'name': 'encodeURI', 'signatures': [['uri']]},
  {'name': 'encodeURIComponent', 'signatures': [['uriComponent']]},
  {'name': 'escape', 'signatures': [['string']]},
  {'name': 'unescape', 'signatures': [['string']]},
  {'name': 'toString', 'signatures': [['?radix']], 'receiver': 'Number'},
  {'name': 'toLocaleString', 'signatures': [['?locales', '?options']], 'receiver': 'Date'},
  {'name': 'toLocaleString', 'signatures': [['?locales', '?options']], 'receiver': 'Number'},
  {'name': 'hasOwnProperty', 'signatures': [['v']]},
  {'name': 'isPrototypeOf', 'signatures': [['v']]},
  {'name': 'propertyIsEnumerable', 'signatures': [['v']]},
  {'name': 'getOwnPropertyNames', 'signatures': [['o']]},
  {'name': 'create', 'signatures': [['o', '?properties']]},
  {'name': 'defineProperties', 'signatures': [['o', 'properties']]},
  {'name': 'seal', 'signatures': [['o']]},
  {'name': 'freeze', 'signatures': [['a'], ['f'], ['o']]},
  {'name': 'isSealed', 'signatures': [['o']]},
  {'name': 'isFrozen', 'signatures': [['o']]},
  {'name': 'call', 'signatures': [['thisArg', '...argArray']]},
  {'name': 'bind', 'signatures': [['thisArg', '...argArray']]},
  {'name': 'charAt', 'signatures': [['pos']]},
  {'name': 'charCodeAt', 'signatures': [['index']]},
  {'name': 'concat', 'signatures': [['...strings']], 'receiver': 'String'},
  {'name': 'concat', 'signatures': [['...items']], 'receiver': 'ReadonlyArray'},
  {'name': 'concat', 'signatures': [['...items']], 'receiver': 'Array'},
  {'name': 'indexOf', 'signatures': [['searchString', '?position']], 'receiver': 'String'},
  {'name': 'indexOf', 'signatures': [['searchElement', '?fromIndex']], 'receiver': 'ReadonlyArray'},
  {'name': 'indexOf', 'signatures': [['searchElement', '?fromIndex']], 'receiver': 'Array'},
  {'name': 'indexOf', 'signatures': [['searchElement', '?fromIndex']], 'receiver': 'Int8Array'},
  {'name': 'indexOf', 'signatures': [['searchElement', '?fromIndex']], 'receiver': 'Uint8Array'},
  {'name': 'indexOf', 'signatures': [['searchElement', '?fromIndex']], 'receiver': 'Uint8ClampedArray'},
  {'name': 'indexOf', 'signatures': [['searchElement', '?fromIndex']], 'receiver': 'Int16Array'},
  {'name': 'indexOf', 'signatures': [['searchElement', '?fromIndex']], 'receiver': 'Uint16Array'},
  {'name': 'indexOf', 'signatures': [['searchElement', '?fromIndex']], 'receiver': 'Int32Array'},
  {'name': 'indexOf', 'signatures': [['searchElement', '?fromIndex']], 'receiver': 'Uint32Array'},
  {'name': 'indexOf', 'signatures': [['searchElement', '?fromIndex']], 'receiver': 'Float32Array'},
  {'name': 'indexOf', 'signatures': [['searchElement', '?fromIndex']], 'receiver': 'Float64Array'},
  {'name': 'lastIndexOf', 'signatures': [['searchString', '?position']], 'receiver': 'String'},
  {'name': 'lastIndexOf', 'signatures': [['searchElement', '?fromIndex']], 'receiver': 'ReadonlyArray'},
  {'name': 'lastIndexOf', 'signatures': [['searchElement', '?fromIndex']], 'receiver': 'Array'},
  {'name': 'lastIndexOf', 'signatures': [['searchElement', '?fromIndex']], 'receiver': 'Int8Array'},
  {'name': 'lastIndexOf', 'signatures': [['searchElement', '?fromIndex']], 'receiver': 'Uint8Array'},
  {'name': 'lastIndexOf', 'signatures': [['searchElement', '?fromIndex']], 'receiver': 'Uint8ClampedArray'},
  {'name': 'lastIndexOf', 'signatures': [['searchElement', '?fromIndex']], 'receiver': 'Int16Array'},
  {'name': 'lastIndexOf', 'signatures': [['searchElement', '?fromIndex']], 'receiver': 'Uint16Array'},
  {'name': 'lastIndexOf', 'signatures': [['searchElement', '?fromIndex']], 'receiver': 'Int32Array'},
  {'name': 'lastIndexOf', 'signatures': [['searchElement', '?fromIndex']], 'receiver': 'Uint32Array'},
  {'name': 'lastIndexOf', 'signatures': [['searchElement', '?fromIndex']], 'receiver': 'Float32Array'},
  {'name': 'lastIndexOf', 'signatures': [['searchElement', '?fromIndex']], 'receiver': 'Float64Array'},
  {'name': 'localeCompare', 'signatures': [['that', '?locales', '?options']]},
  {'name': 'slice', 'signatures': [['?start', '?end']], 'receiver': 'String'},
  {'name': 'slice', 'signatures': [['?start', '?end']], 'receiver': 'ReadonlyArray'},
  {'name': 'slice', 'signatures': [['?start', '?end']], 'receiver': 'ConcatArray'},
  {'name': 'slice', 'signatures': [['?start', '?end']], 'receiver': 'Array'},
  {'name': 'slice', 'signatures': [['begin', '?end']], 'receiver': 'ArrayBuffer'},
  {'name': 'slice', 'signatures': [['?start', '?end']], 'receiver': 'Int8Array'},
  {'name': 'slice', 'signatures': [['?start', '?end']], 'receiver': 'Uint8Array'},
  {'name': 'slice', 'signatures': [['?start', '?end']], 'receiver': 'Uint8ClampedArray'},
  {'name': 'slice', 'signatures': [['?start', '?end']], 'receiver': 'Int16Array'},
  {'name': 'slice', 'signatures': [['?start', '?end']], 'receiver': 'Uint16Array'},
  {'name': 'slice', 'signatures': [['?start', '?end']], 'receiver': 'Int32Array'},
  {'name': 'slice', 'signatures': [['?start', '?end']], 'receiver': 'Uint32Array'},
  {'name': 'slice', 'signatures': [['?start', '?end']], 'receiver': 'Float32Array'},
  {'name': 'slice', 'signatures': [['?start', '?end']], 'receiver': 'Float64Array'},
  {'name': 'slice', 'signatures': [['begin', '?end']], 'receiver': 'SharedArrayBuffer'},
  {'name': 'substring', 'signatures': [['start', '?end']]},
  {'name': 'substr', 'signatures': [['from', '?length']]},
  {'name': 'fromCharCode', 'signatures': [['...codes']]},
  {'name': 'toFixed', 'signatures': [['?fractionDigits']]},
  {'name': 'toExponential', 'signatures': [['?fractionDigits']]},
  {'name': 'toPrecision', 'signatures': [['?precision']]},
  {'name': 'abs', 'signatures': [['x']]},
  {'name': 'acos', 'signatures': [['x']]},
  {'name': 'asin', 'signatures': [['x']]},
  {'name': 'atan', 'signatures': [['x']]},
  {'name': 'atan2', 'signatures': [['y', 'x']]},
  {'name': 'ceil', 'signatures': [['x']]},
  {'name': 'cos', 'signatures': [['x']]},
  {'name': 'exp', 'signatures': [['x']]},
  {'name': 'floor', 'signatures': [['x']]},
  {'name': 'log', 'signatures': [['x']], 'receiver': 'Math'},
  {'name': 'log', 'signatures': [['...data']], 'receiver': 'console'},
  {'name': 'max', 'signatures': [['...values']]},
  {'name': 'min', 'signatures': [['...values']]},
  {'name': 'pow', 'signatures': [['x', 'y']]},
  {'name': 'round', 'signatures': [['x']]},
  {'name': 'sin', 'signatures': [['x']]},
  {'name': 'sqrt', 'signatures': [['x']]},
  {'name': 'tan', 'signatures': [['x']]},
  {'name': 'toLocaleDateString', 'signatures': [['?locales', '?options']]},
  {'name': 'toLocaleTimeString', 'signatures': [['?locales', '?options']]},
  {'name': 'setTime', 'signatures': [['time']]},
  {'name': 'setMilliseconds', 'signatures': [['ms']]},
  {'name': 'setUTCMilliseconds', 'signatures': [['ms']]},
  {'name': 'setSeconds', 'signatures': [['sec', '?ms']]},
  {'name': 'setUTCSeconds', 'signatures': [['sec', '?ms']]},
  {'name': 'setMinutes', 'signatures': [['min', '?sec', '?ms']]},
  {'name': 'setUTCMinutes', 'signatures': [['min', '?sec', '?ms']]},
  {'name': 'setHours', 'signatures': [['hours', '?min', '?sec', '?ms']]},
  {'name': 'setUTCHours', 'signatures': [['hours', '?min', '?sec', '?ms']]},
  {'name': 'setDate', 'signatures': [['date']]},
  {'name': 'setUTCDate', 'signatures': [['date']]},
  {'name': 'setMonth', 'signatures': [['month', '?date']]},
  {'name': 'setUTCMonth', 'signatures': [['month', '?date']]},
  {'name': 'setFullYear', 'signatures': [['year', '?month', '?date']]},
  {'name': 'setUTCFullYear', 'signatures': [['year', '?month', '?date']]},
  {'name': 'toJSON', 'signatures': [['?key']]},
  {'name': 'parse', 'signatures': [['s']], 'static': true, 'receiver': 'Date'},
  {'name': 'parse', 'signatures': [['text', '?reviver']], 'receiver': 'JSON'},
  {'name': 'UTC', 'signatures': [['year', 'month', '?date', '?hours', '?minutes', '?seconds', '?ms']]},
  {'name': 'exec', 'signatures': [['string']]},
  {'name': 'test', 'signatures': [['string']]},
  {'name': 'stringify', 'signatures': [['value', '?replacer', '?space']]},
  {'name': 'join', 'signatures': [['?separator']]},
  {'name': 'every', 'signatures': [['callbackfn', '?thisArg']]},
  {'name': 'some', 'signatures': [['callbackfn', '?thisArg']]},
  {'name': 'map', 'signatures': [['callbackfn', '?thisArg']]},
  {'name': 'filter', 'signatures': [['callbackfn', '?thisArg']]},
  {'name': 'reduce', 'signatures': [['callbackfn', '?initialValue']]},
  {'name': 'reduceRight', 'signatures': [['callbackfn', '?initialValue']]},
  {'name': 'push', 'signatures': [['...items']]},
  {'name': 'sort', 'signatures': [['?compareFn']]},
  {'name': 'splice', 'signatures': [['start', '?deleteCount', '...items']]},
  {'name': 'unshift', 'signatures': [['...items']]},
  {'name': 'isArray', 'signatures': [['arg']]},
  {'name': 'then', 'signatures': [['?onfulfilled', '?onrejected']]},
  {'name': 'catch', 'signatures': [['?onrejected']]},
  {'name': 'isView', 'signatures': [['arg']]},
  {'name': 'getFloat32', 'signatures': [['byteOffset', '?littleEndian']]},
  {'name': 'getFloat64', 'signatures': [['byteOffset', '?littleEndian']]},
  {'name': 'getInt8', 'signatures': [['byteOffset']]},
  {'name': 'getInt16', 'signatures': [['byteOffset', '?littleEndian']]},
  {'name': 'getInt32', 'signatures': [['byteOffset', '?littleEndian']]},
  {'name': 'getUint8', 'signatures': [['byteOffset']]},
  {'name': 'getUint16', 'signatures': [['byteOffset', '?littleEndian']]},
  {'name': 'getUint32', 'signatures': [['byteOffset', '?littleEndian']]},
  {'name': 'setFloat32', 'signatures': [['byteOffset', 'value', '?littleEndian']]},
  {'name': 'setFloat64', 'signatures': [['byteOffset', 'value', '?littleEndian']]},
  {'name': 'setInt8', 'signatures': [['byteOffset', 'value']]},
  {'name': 'setInt16', 'signatures': [['byteOffset', 'value', '?littleEndian']]},
  {'name': 'setInt32', 'signatures': [['byteOffset', 'value', '?littleEndian']]},
  {'name': 'setUint8', 'signatures': [['byteOffset', 'value']]},
  {'name': 'setUint16', 'signatures': [['byteOffset', 'value', '?littleEndian']]},
  {'name': 'setUint32', 'signatures': [['byteOffset', 'value', '?littleEndian']]},
  {'name': 'subarray', 'signatures': [['begin', '?end']]},
  {'name': 'getOwnPropertyDescriptors', 'signatures': [['o']]},
  {'name': 'and', 'signatures': [['typedArray', 'index', 'value']]},
  {'name': 'compareExchange', 'signatures': [['typedArray', 'index', 'expectedValue', 'replacementValue']]},
  {'name': 'exchange', 'signatures': [['typedArray', 'index', 'value']]},
  {'name': 'isLockFree', 'signatures': [['size']]},
  {'name': 'load', 'signatures': [['typedArray', 'index']]},
  {'name': 'or', 'signatures': [['typedArray', 'index', 'value']]},
  {'name': 'store', 'signatures': [['typedArray', 'index', 'value']]},
  {'name': 'wait', 'signatures': [['typedArray', 'index', 'value', '?timeout']]},
  {'name': 'wake', 'signatures': [['typedArray', 'index', 'count']]},
  {'name': 'xor', 'signatures': [['typedArray', 'index', 'value']]},
  {'name': 'padStart', 'signatures': [['maxLength', '?fillString']]},
  {'name': 'padEnd', 'signatures': [['maxLength', '?fillString']]},
  {'name': 'finally', 'signatures': [['?onfinally']]},
  {'name': 'flatMap', 'signatures': [['callback', '?thisArg']]},
  {'name': 'flatten', 'signatures': [['?depth']]},
  {'name': 'assert', 'signatures': [['?condition', '...data']]},
  {'name': 'count', 'signatures': [['?label']]},
  {'name': 'debug', 'signatures': [['...data']]},
  {'name': 'dir', 'signatures': [['item', '?options']]},
  {'name': 'dirxml', 'signatures': [['...data']]},
  {'name': 'error', 'signatures': [['...data']]},
  {'name': 'group', 'signatures': [['...data']]},
  {'name': 'groupCollapsed', 'signatures': [['...data']]},
  {'name': 'info', 'signatures': [['...data']]},
  {'name': 'profile', 'signatures': [['?title']]},
  {'name': 'profileEnd', 'signatures': [['?title']]},
  {'name': 'table', 'signatures': [['...tabularData']]},
  {'name': 'time', 'signatures': [['?label']]},
  {'name': 'timeEnd', 'signatures': [['?label']]},
  {'name': 'timeStamp', 'signatures': [['?name']]},
  {'name': 'trace', 'signatures': [['...data']]},
  {'name': 'warn', 'signatures': [['...data']]}
];
