// Copyright 2020 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
// Generated from javascript_natives/helpers.js

export const NativeFunctions = [
  {'name': 'find', 'signatures': [['predicate', '?thisArg']]},
  {'name': 'findIndex', 'signatures': [['predicate', '?thisArg']]},
  {'name': 'fill', 'signatures': [['value', '?start', '?end']]},
  {'name': 'copyWithin', 'signatures': [['target', 'start', '?end']]},
  {
    'name': 'from',
    'signatures': [['arrayLike', '?mapfn', '?thisArg'], ['iterable', '?mapfn', '?thisArg']],
    'static': true,
    'receiver': 'Array'
  },
  {'name': 'from', 'signatures': [['arrayLike', '?mapfn', '?thisArg']], 'static': true, 'receiver': 'Int8Array'},
  {'name': 'from', 'signatures': [['arrayLike', '?mapfn', '?thisArg']], 'static': true, 'receiver': 'Uint8Array'},
  {
    'name': 'from',
    'signatures': [['arrayLike', '?mapfn', '?thisArg']],
    'static': true,
    'receiver': 'Uint8ClampedArray'
  },
  {'name': 'from', 'signatures': [['arrayLike', '?mapfn', '?thisArg']], 'static': true, 'receiver': 'Int16Array'},
  {'name': 'from', 'signatures': [['arrayLike', '?mapfn', '?thisArg']], 'static': true, 'receiver': 'Uint16Array'},
  {'name': 'from', 'signatures': [['arrayLike', '?mapfn', '?thisArg']], 'static': true, 'receiver': 'Int32Array'},
  {'name': 'from', 'signatures': [['arrayLike', '?mapfn', '?thisArg']], 'static': true, 'receiver': 'Uint32Array'},
  {'name': 'from', 'signatures': [['arrayLike', '?mapfn', '?thisArg']], 'static': true, 'receiver': 'Float32Array'},
  {'name': 'from', 'signatures': [['arrayLike', '?mapfn', '?thisArg']], 'static': true, 'receiver': 'Float64Array'},
  {'name': 'of', 'signatures': [['...items']]},
  {'name': 'clz32', 'signatures': [['x']]},
  {'name': 'imul', 'signatures': [['x', 'y']]},
  {'name': 'sign', 'signatures': [['x']]},
  {'name': 'log10', 'signatures': [['x']]},
  {'name': 'log2', 'signatures': [['x']]},
  {'name': 'log1p', 'signatures': [['x']]},
  {'name': 'expm1', 'signatures': [['x']]},
  {'name': 'cosh', 'signatures': [['x']]},
  {'name': 'sinh', 'signatures': [['x']]},
  {'name': 'tanh', 'signatures': [['x']]},
  {'name': 'acosh', 'signatures': [['x']]},
  {'name': 'asinh', 'signatures': [['x']]},
  {'name': 'atanh', 'signatures': [['x']]},
  {'name': 'hypot', 'signatures': [['...values']]},
  {'name': 'trunc', 'signatures': [['x']]},
  {'name': 'fround', 'signatures': [['x']]},
  {'name': 'cbrt', 'signatures': [['x']]},
  {'name': 'isFinite', 'signatures': [['number']]},
  {'name': 'isInteger', 'signatures': [['number']]},
  {'name': 'isNaN', 'signatures': [['number']]},
  {'name': 'isSafeInteger', 'signatures': [['number']]},
  {'name': 'parseFloat', 'signatures': [['string']]},
  {'name': 'parseInt', 'signatures': [['string', '?radix']], 'static': true, 'receiver': 'Number'},
  {'name': 'parseInt', 'signatures': [['s', '?radix']], 'receiver': 'Window'},
  {
    'name': 'assign',
    'signatures': [['target', 'source'], ['target', '...sources'], ['target', 'source1', 'source2', '?source3']]
  },
  {'name': 'getOwnPropertySymbols', 'signatures': [['o']]},
  {'name': 'is', 'signatures': [['value1', 'value2']]},
  {'name': 'setPrototypeOf', 'signatures': [['o', 'proto']], 'static': true, 'receiver': 'Object'},
  {'name': 'setPrototypeOf', 'signatures': [['target', 'v']], 'receiver': 'ProxyHandler'},
  {'name': 'codePointAt', 'signatures': [['pos']]},
  {'name': 'includes', 'signatures': [['searchString', '?position']], 'receiver': 'String'},
  {'name': 'includes', 'signatures': [['searchElement', '?fromIndex']], 'receiver': 'Array'},
  {'name': 'includes', 'signatures': [['searchElement', '?fromIndex']], 'receiver': 'ReadonlyArray'},
  {'name': 'includes', 'signatures': [['searchElement', '?fromIndex']], 'receiver': 'Int8Array'},
  {'name': 'includes', 'signatures': [['searchElement', '?fromIndex']], 'receiver': 'Uint8Array'},
  {'name': 'includes', 'signatures': [['searchElement', '?fromIndex']], 'receiver': 'Uint8ClampedArray'},
  {'name': 'includes', 'signatures': [['searchElement', '?fromIndex']], 'receiver': 'Int16Array'},
  {'name': 'includes', 'signatures': [['searchElement', '?fromIndex']], 'receiver': 'Uint16Array'},
  {'name': 'includes', 'signatures': [['searchElement', '?fromIndex']], 'receiver': 'Int32Array'},
  {'name': 'includes', 'signatures': [['searchElement', '?fromIndex']], 'receiver': 'Uint32Array'},
  {'name': 'includes', 'signatures': [['searchElement', '?fromIndex']], 'receiver': 'Float32Array'},
  {'name': 'includes', 'signatures': [['searchElement', '?fromIndex']], 'receiver': 'Float64Array'},
  {'name': 'endsWith', 'signatures': [['searchString', '?endPosition']]},
  {'name': 'normalize', 'signatures': [['?form']]},
  {'name': 'repeat', 'signatures': [['count']]},
  {'name': 'startsWith', 'signatures': [['searchString', '?position']]},
  {'name': 'anchor', 'signatures': [['name']]},
  {'name': 'fontcolor', 'signatures': [['color']]},
  {'name': 'fontsize', 'signatures': [['size']]},
  {'name': 'link', 'signatures': [['url']]},
  {'name': 'sub', 'signatures': [['typedArray', 'index', 'value']], 'receiver': 'Atomics'},
  {'name': 'fromCodePoint', 'signatures': [['...codePoints']]},
  {'name': 'raw', 'signatures': [['template', '...substitutions']]},
  {'name': 'delete', 'signatures': [['key']], 'receiver': 'Map'},
  {'name': 'delete', 'signatures': [['key']], 'receiver': 'WeakMap'},
  {'name': 'delete', 'signatures': [['value']], 'receiver': 'Set'},
  {'name': 'delete', 'signatures': [['value']], 'receiver': 'WeakSet'},
  {'name': 'forEach', 'signatures': [['callbackfn', '?thisArg']]},
  {'name': 'get', 'signatures': [['key']], 'receiver': 'Map'},
  {'name': 'get', 'signatures': [['key']], 'receiver': 'ReadonlyMap'},
  {'name': 'get', 'signatures': [['key']], 'receiver': 'WeakMap'},
  {'name': 'get', 'signatures': [['target', 'p', 'receiver']], 'receiver': 'ProxyHandler'},
  {'name': 'has', 'signatures': [['key']], 'receiver': 'Map'},
  {'name': 'has', 'signatures': [['key']], 'receiver': 'ReadonlyMap'},
  {'name': 'has', 'signatures': [['key']], 'receiver': 'WeakMap'},
  {'name': 'has', 'signatures': [['value']], 'receiver': 'Set'},
  {'name': 'has', 'signatures': [['value']], 'receiver': 'ReadonlySet'},
  {'name': 'has', 'signatures': [['value']], 'receiver': 'WeakSet'},
  {'name': 'has', 'signatures': [['target', 'p']], 'receiver': 'ProxyHandler'},
  {'name': 'set', 'signatures': [['key', 'value']], 'receiver': 'Map'},
  {'name': 'set', 'signatures': [['key', 'value']], 'receiver': 'WeakMap'},
  {'name': 'set', 'signatures': [['target', 'p', 'value', 'receiver']], 'receiver': 'ProxyHandler'},
  {'name': 'set', 'signatures': [['v']], 'receiver': 'PropertyDescriptor'},
  {'name': 'set', 'signatures': [['array', '?offset']], 'receiver': 'Int8Array'},
  {'name': 'set', 'signatures': [['array', '?offset']], 'receiver': 'Uint8Array'},
  {'name': 'set', 'signatures': [['array', '?offset']], 'receiver': 'Uint8ClampedArray'},
  {'name': 'set', 'signatures': [['array', '?offset']], 'receiver': 'Int16Array'},
  {'name': 'set', 'signatures': [['array', '?offset']], 'receiver': 'Uint16Array'},
  {'name': 'set', 'signatures': [['array', '?offset']], 'receiver': 'Int32Array'},
  {'name': 'set', 'signatures': [['array', '?offset']], 'receiver': 'Uint32Array'},
  {'name': 'set', 'signatures': [['array', '?offset']], 'receiver': 'Float32Array'},
  {'name': 'set', 'signatures': [['array', '?offset']], 'receiver': 'Float64Array'},
  {'name': 'add', 'signatures': [['value']], 'receiver': 'Set'},
  {'name': 'add', 'signatures': [['value']], 'receiver': 'WeakSet'},
  {'name': 'add', 'signatures': [['typedArray', 'index', 'value']], 'receiver': 'Atomics'},
  {'name': 'all', 'signatures': [['values']]},
  {'name': 'race', 'signatures': [['values']]},
  {'name': 'reject', 'signatures': [['?reason']]},
  {'name': 'resolve', 'signatures': [['?value']]},
  {'name': 'for', 'signatures': [['key']]},
  {'name': 'keyFor', 'signatures': [['sym']]},
  {'name': 'next', 'signatures': [['?value']]},
  {'name': 'return', 'signatures': [['?value']]},
  {'name': 'throw', 'signatures': [['?e']]},
  {'name': 'entries', 'signatures': [['o']], 'static': true, 'receiver': 'Object'},
  {'name': 'keys', 'signatures': [['o']], 'static': true, 'receiver': 'Object'},
  {'name': 'values', 'signatures': [['o']], 'static': true, 'receiver': 'Object'},
  {'name': 'getPrototypeOf', 'signatures': [['target']], 'receiver': 'ProxyHandler'},
  {'name': 'getPrototypeOf', 'signatures': [['o']], 'static': true, 'receiver': 'Object'},
  {'name': 'isExtensible', 'signatures': [['target']], 'receiver': 'ProxyHandler'},
  {'name': 'isExtensible', 'signatures': [['o']], 'static': true, 'receiver': 'Object'},
  {'name': 'preventExtensions', 'signatures': [['target']], 'receiver': 'ProxyHandler'},
  {'name': 'preventExtensions', 'signatures': [['o']], 'static': true, 'receiver': 'Object'},
  {'name': 'getOwnPropertyDescriptor', 'signatures': [['target', 'p']], 'receiver': 'ProxyHandler'},
  {'name': 'getOwnPropertyDescriptor', 'signatures': [['o', 'p']], 'static': true, 'receiver': 'Object'},
  {'name': 'deleteProperty', 'signatures': [['target', 'p']]},
  {'name': 'defineProperty', 'signatures': [['target', 'p', 'attributes']], 'receiver': 'ProxyHandler'},
  {'name': 'defineProperty', 'signatures': [['o', 'p', 'attributes']], 'static': true, 'receiver': 'Object'},
  {'name': 'enumerate', 'signatures': [['target']]},
  {'name': 'ownKeys', 'signatures': [['target']]},
  {'name': 'apply', 'signatures': [['target', 'thisArg', '?argArray']], 'receiver': 'ProxyHandler'},
  {'name': 'apply', 'signatures': [['thisArg', '?argArray']], 'receiver': 'Function'},
  {'name': 'construct', 'signatures': [['target', 'argArray', '?newTarget']]},
  {'name': 'revocable', 'signatures': [['target', 'handler']]},
  {'name': 'match', 'signatures': [['matcher'], ['regexp']]},
  {'name': 'replace', 'signatures': [['searchValue', 'replaceValue'], ['searchValue', 'replacer']]},
  {'name': 'search', 'signatures': [['searcher'], ['regexp']]},
  {'name': 'split', 'signatures': [['splitter', '?limit'], ['separator', '?limit']]},
  {'name': 'eval', 'signatures': [['x']]},
  {'name': 'decodeURI', 'signatures': [['encodedURI']]},
  {'name': 'decodeURIComponent', 'signatures': [['encodedURIComponent']]},
  {'name': 'encodeURI', 'signatures': [['uri']]},
  {'name': 'encodeURIComponent', 'signatures': [['uriComponent']]},
  {'name': 'escape', 'signatures': [['string']], 'receiver': 'Window'},
  {'name': 'escape', 'signatures': [['ident']], 'receiver': 'CSS'},
  {'name': 'unescape', 'signatures': [['string']]},
  {'name': 'toString', 'signatures': [['?radix']], 'receiver': 'Number'},
  {'name': 'toLocaleString', 'signatures': [['?locales', '?options']], 'receiver': 'Date'},
  {'name': 'toLocaleString', 'signatures': [['?locales', '?options']], 'receiver': 'Number'},
  {'name': 'hasOwnProperty', 'signatures': [['v']]},
  {'name': 'isPrototypeOf', 'signatures': [['v']]},
  {'name': 'propertyIsEnumerable', 'signatures': [['v']]},
  {'name': 'getOwnPropertyNames', 'signatures': [['o']]},
  {'name': 'create', 'signatures': [['o', '?properties']]},
  {'name': 'defineProperties', 'signatures': [['o', 'properties']]},
  {'name': 'seal', 'signatures': [['o']]},
  {'name': 'freeze', 'signatures': [['a'], ['f'], ['o']]},
  {'name': 'isSealed', 'signatures': [['o']]},
  {'name': 'isFrozen', 'signatures': [['o']]},
  {'name': 'call', 'signatures': [['thisArg', '...argArray']]},
  {'name': 'bind', 'signatures': [['thisArg', '...argArray']]},
  {'name': 'charAt', 'signatures': [['pos']]},
  {'name': 'charCodeAt', 'signatures': [['index']]},
  {'name': 'concat', 'signatures': [['...strings']], 'receiver': 'String'},
  {'name': 'concat', 'signatures': [['...items']], 'receiver': 'ReadonlyArray'},
  {'name': 'concat', 'signatures': [['...items']], 'receiver': 'Array'},
  {'name': 'indexOf', 'signatures': [['searchString', '?position']], 'receiver': 'String'},
  {'name': 'indexOf', 'signatures': [['searchElement', '?fromIndex']], 'receiver': 'ReadonlyArray'},
  {'name': 'indexOf', 'signatures': [['searchElement', '?fromIndex']], 'receiver': 'Array'},
  {'name': 'indexOf', 'signatures': [['searchElement', '?fromIndex']], 'receiver': 'Int8Array'},
  {'name': 'indexOf', 'signatures': [['searchElement', '?fromIndex']], 'receiver': 'Uint8Array'},
  {'name': 'indexOf', 'signatures': [['searchElement', '?fromIndex']], 'receiver': 'Uint8ClampedArray'},
  {'name': 'indexOf', 'signatures': [['searchElement', '?fromIndex']], 'receiver': 'Int16Array'},
  {'name': 'indexOf', 'signatures': [['searchElement', '?fromIndex']], 'receiver': 'Uint16Array'},
  {'name': 'indexOf', 'signatures': [['searchElement', '?fromIndex']], 'receiver': 'Int32Array'},
  {'name': 'indexOf', 'signatures': [['searchElement', '?fromIndex']], 'receiver': 'Uint32Array'},
  {'name': 'indexOf', 'signatures': [['searchElement', '?fromIndex']], 'receiver': 'Float32Array'},
  {'name': 'indexOf', 'signatures': [['searchElement', '?fromIndex']], 'receiver': 'Float64Array'},
  {'name': 'lastIndexOf', 'signatures': [['searchString', '?position']], 'receiver': 'String'},
  {'name': 'lastIndexOf', 'signatures': [['searchElement', '?fromIndex']], 'receiver': 'ReadonlyArray'},
  {'name': 'lastIndexOf', 'signatures': [['searchElement', '?fromIndex']], 'receiver': 'Array'},
  {'name': 'lastIndexOf', 'signatures': [['searchElement', '?fromIndex']], 'receiver': 'Int8Array'},
  {'name': 'lastIndexOf', 'signatures': [['searchElement', '?fromIndex']], 'receiver': 'Uint8Array'},
  {'name': 'lastIndexOf', 'signatures': [['searchElement', '?fromIndex']], 'receiver': 'Uint8ClampedArray'},
  {'name': 'lastIndexOf', 'signatures': [['searchElement', '?fromIndex']], 'receiver': 'Int16Array'},
  {'name': 'lastIndexOf', 'signatures': [['searchElement', '?fromIndex']], 'receiver': 'Uint16Array'},
  {'name': 'lastIndexOf', 'signatures': [['searchElement', '?fromIndex']], 'receiver': 'Int32Array'},
  {'name': 'lastIndexOf', 'signatures': [['searchElement', '?fromIndex']], 'receiver': 'Uint32Array'},
  {'name': 'lastIndexOf', 'signatures': [['searchElement', '?fromIndex']], 'receiver': 'Float32Array'},
  {'name': 'lastIndexOf', 'signatures': [['searchElement', '?fromIndex']], 'receiver': 'Float64Array'},
  {'name': 'localeCompare', 'signatures': [['that', '?locales', '?options']]},
  {'name': 'slice', 'signatures': [['?start', '?end']], 'receiver': 'String'},
  {'name': 'slice', 'signatures': [['?start', '?end']], 'receiver': 'ReadonlyArray'},
  {'name': 'slice', 'signatures': [['?start', '?end']], 'receiver': 'ConcatArray'},
  {'name': 'slice', 'signatures': [['?start', '?end']], 'receiver': 'Array'},
  {'name': 'slice', 'signatures': [['begin', '?end']], 'receiver': 'ArrayBuffer'},
  {'name': 'slice', 'signatures': [['?start', '?end']], 'receiver': 'Int8Array'},
  {'name': 'slice', 'signatures': [['?start', '?end']], 'receiver': 'Uint8Array'},
  {'name': 'slice', 'signatures': [['?start', '?end']], 'receiver': 'Uint8ClampedArray'},
  {'name': 'slice', 'signatures': [['?start', '?end']], 'receiver': 'Int16Array'},
  {'name': 'slice', 'signatures': [['?start', '?end']], 'receiver': 'Uint16Array'},
  {'name': 'slice', 'signatures': [['?start', '?end']], 'receiver': 'Int32Array'},
  {'name': 'slice', 'signatures': [['?start', '?end']], 'receiver': 'Uint32Array'},
  {'name': 'slice', 'signatures': [['?start', '?end']], 'receiver': 'Float32Array'},
  {'name': 'slice', 'signatures': [['?start', '?end']], 'receiver': 'Float64Array'},
  {'name': 'slice', 'signatures': [['begin', '?end']], 'receiver': 'SharedArrayBuffer'},
  {'name': 'substring', 'signatures': [['start', '?end']]},
  {'name': 'substr', 'signatures': [['from', '?length']]},
  {'name': 'fromCharCode', 'signatures': [['...codes']]},
  {'name': 'toFixed', 'signatures': [['?fractionDigits']]},
  {'name': 'toExponential', 'signatures': [['?fractionDigits']]},
  {'name': 'toPrecision', 'signatures': [['?precision']]},
  {'name': 'abs', 'signatures': [['x']]},
  {'name': 'acos', 'signatures': [['x']]},
  {'name': 'asin', 'signatures': [['x']]},
  {'name': 'atan', 'signatures': [['x']]},
  {'name': 'atan2', 'signatures': [['y', 'x']]},
  {'name': 'ceil', 'signatures': [['x']]},
  {'name': 'cos', 'signatures': [['x']]},
  {'name': 'exp', 'signatures': [['x']]},
  {'name': 'floor', 'signatures': [['x']]},
  {'name': 'log', 'signatures': [['x']], 'receiver': 'Math'},
  {'name': 'log', 'signatures': [['...data']], 'receiver': 'console'},
  {'name': 'max', 'signatures': [['...values']]},
  {'name': 'min', 'signatures': [['...values']]},
  {'name': 'pow', 'signatures': [['x', 'y']]},
  {'name': 'round', 'signatures': [['x']]},
  {'name': 'sin', 'signatures': [['x']]},
  {'name': 'sqrt', 'signatures': [['x']]},
  {'name': 'tan', 'signatures': [['x']]},
  {'name': 'toLocaleDateString', 'signatures': [['?locales', '?options']]},
  {'name': 'toLocaleTimeString', 'signatures': [['?locales', '?options']]},
  {'name': 'setTime', 'signatures': [['time']]},
  {'name': 'setMilliseconds', 'signatures': [['ms']]},
  {'name': 'setUTCMilliseconds', 'signatures': [['ms']]},
  {'name': 'setSeconds', 'signatures': [['sec', '?ms']]},
  {'name': 'setUTCSeconds', 'signatures': [['sec', '?ms']]},
  {'name': 'setMinutes', 'signatures': [['min', '?sec', '?ms']]},
  {'name': 'setUTCMinutes', 'signatures': [['min', '?sec', '?ms']]},
  {'name': 'setHours', 'signatures': [['hours', '?min', '?sec', '?ms']]},
  {'name': 'setUTCHours', 'signatures': [['hours', '?min', '?sec', '?ms']]},
  {'name': 'setDate', 'signatures': [['date']]},
  {'name': 'setUTCDate', 'signatures': [['date']]},
  {'name': 'setMonth', 'signatures': [['month', '?date']]},
  {'name': 'setUTCMonth', 'signatures': [['month', '?date']]},
  {'name': 'setFullYear', 'signatures': [['year', '?month', '?date']]},
  {'name': 'setUTCFullYear', 'signatures': [['year', '?month', '?date']]},
  {'name': 'toJSON', 'signatures': [['?key']]},
  {'name': 'parse', 'signatures': [['s']], 'static': true, 'receiver': 'Date'},
  {'name': 'parse', 'signatures': [['text', '?reviver']], 'receiver': 'JSON'},
  {'name': 'UTC', 'signatures': [['year', 'month', '?date', '?hours', '?minutes', '?seconds', '?ms']]},
  {'name': 'exec', 'signatures': [['string']]},
  {'name': 'test', 'signatures': [['string']]},
  {'name': 'stringify', 'signatures': [['value', '?replacer', '?space']]},
  {'name': 'join', 'signatures': [['?separator']]},
  {'name': 'every', 'signatures': [['callbackfn', '?thisArg']]},
  {'name': 'some', 'signatures': [['callbackfn', '?thisArg']]},
  {'name': 'map', 'signatures': [['callbackfn', '?thisArg']]},
  {'name': 'filter', 'signatures': [['callbackfn', '?thisArg']]},
  {'name': 'reduce', 'signatures': [['callbackfn', '?initialValue']]},
  {'name': 'reduceRight', 'signatures': [['callbackfn', '?initialValue']]},
  {'name': 'push', 'signatures': [['...items']]},
  {'name': 'sort', 'signatures': [['?compareFn']]},
  {'name': 'splice', 'signatures': [['start', '?deleteCount', '...items']]},
  {'name': 'unshift', 'signatures': [['...items']]},
  {'name': 'isArray', 'signatures': [['arg']]},
  {'name': 'then', 'signatures': [['?onfulfilled', '?onrejected']]},
  {'name': 'catch', 'signatures': [['?onrejected']]},
  {'name': 'isView', 'signatures': [['arg']]},
  {'name': 'getFloat32', 'signatures': [['byteOffset', '?littleEndian']]},
  {'name': 'getFloat64', 'signatures': [['byteOffset', '?littleEndian']]},
  {'name': 'getInt8', 'signatures': [['byteOffset']]},
  {'name': 'getInt16', 'signatures': [['byteOffset', '?littleEndian']]},
  {'name': 'getInt32', 'signatures': [['byteOffset', '?littleEndian']]},
  {'name': 'getUint8', 'signatures': [['byteOffset']]},
  {'name': 'getUint16', 'signatures': [['byteOffset', '?littleEndian']]},
  {'name': 'getUint32', 'signatures': [['byteOffset', '?littleEndian']]},
  {'name': 'setFloat32', 'signatures': [['byteOffset', 'value', '?littleEndian']]},
  {'name': 'setFloat64', 'signatures': [['byteOffset', 'value', '?littleEndian']]},
  {'name': 'setInt8', 'signatures': [['byteOffset', 'value']]},
  {'name': 'setInt16', 'signatures': [['byteOffset', 'value', '?littleEndian']]},
  {'name': 'setInt32', 'signatures': [['byteOffset', 'value', '?littleEndian']]},
  {'name': 'setUint8', 'signatures': [['byteOffset', 'value']]},
  {'name': 'setUint16', 'signatures': [['byteOffset', 'value', '?littleEndian']]},
  {'name': 'setUint32', 'signatures': [['byteOffset', 'value', '?littleEndian']]},
  {'name': 'subarray', 'signatures': [['begin', '?end']]},
  {'name': 'getOwnPropertyDescriptors', 'signatures': [['o']]},
  {'name': 'and', 'signatures': [['typedArray', 'index', 'value']]},
  {'name': 'compareExchange', 'signatures': [['typedArray', 'index', 'expectedValue', 'replacementValue']]},
  {'name': 'exchange', 'signatures': [['typedArray', 'index', 'value']]},
  {'name': 'isLockFree', 'signatures': [['size']]},
  {'name': 'load', 'signatures': [['typedArray', 'index']]},
  {'name': 'or', 'signatures': [['typedArray', 'index', 'value']]},
  {'name': 'store', 'signatures': [['typedArray', 'index', 'value']]},
  {'name': 'wait', 'signatures': [['typedArray', 'index', 'value', '?timeout']]},
  {'name': 'wake', 'signatures': [['typedArray', 'index', 'count']]},
  {'name': 'xor', 'signatures': [['typedArray', 'index', 'value']]},
  {'name': 'padStart', 'signatures': [['maxLength', '?fillString']]},
  {'name': 'padEnd', 'signatures': [['maxLength', '?fillString']]},
  {'name': 'finally', 'signatures': [['?onfinally']]},
  {'name': 'flatMap', 'signatures': [['callback', '?thisArg']]},
  {'name': 'flatten', 'signatures': [['?depth']]},
  {'name': 'Animation', 'signatures': [['?effect', '?timeline']]},
  {'name': 'DocumentTimeline', 'signatures': [['?options']]},
  {'name': 'KeyframeEffect', 'signatures': [['target', 'keyframes', '?options']]},
  {'name': 'ScrollTimeline', 'signatures': [['?options']]},
  {'name': 'AccessibleNodeList', 'signatures': [['?nodes']]},
  {'name': 'AppHistoryCurrentChangeEvent', 'signatures': [['type', 'eventInit']]},
  {'name': 'AppHistoryNavigateEvent', 'signatures': [['type', 'eventInit']]},
  {'name': 'CSSStyleSheet', 'signatures': [['?options']]},
  {'name': 'supports', 'signatures': [['conditionText'], ['property', 'value']]},
  {'name': 'CSSHSL', 'signatures': [['h', 's', 'l', '?alpha']]},
  {'name': 'CSSKeywordValue', 'signatures': [['keyword']]},
  {'name': 'CSSMathInvert', 'signatures': [['arg']]},
  {'name': 'CSSMathMax', 'signatures': [['...args']]},
  {'name': 'CSSMathMin', 'signatures': [['...args']]},
  {'name': 'CSSMathNegate', 'signatures': [['arg']]},
  {'name': 'CSSMathProduct', 'signatures': [['...args']]},
  {'name': 'CSSMathSum', 'signatures': [['...args']]},
  {'name': 'CSSMatrixComponent', 'signatures': [['matrix', '?options']]},
  {'name': 'CSSPerspective', 'signatures': [['length']]},
  {'name': 'CSSPositionValue', 'signatures': [['x', 'y']]},
  {'name': 'CSSRGB', 'signatures': [['r', 'g', 'b', '?alpha']]},
  {'name': 'CSSRotate', 'signatures': [['angleValue']]},
  {'name': 'CSSScale', 'signatures': [['x', 'y', '?z']]},
  {'name': 'CSSSkewX', 'signatures': [['ax']]},
  {'name': 'CSSSkewY', 'signatures': [['ay']]},
  {'name': 'CSSSkew', 'signatures': [['ax', 'ay']]},
  {'name': 'CSSTransformValue', 'signatures': [['transforms']]},
  {'name': 'CSSTranslate', 'signatures': [['x', 'y', '?z']]},
  {'name': 'CSSUnitValue', 'signatures': [['value', 'unit']]},
  {'name': 'number', 'signatures': [['value']]},
  {'name': 'percent', 'signatures': [['value']]},
  {'name': 'em', 'signatures': [['value']]},
  {'name': 'ex', 'signatures': [['value']]},
  {'name': 'ch', 'signatures': [['value']]},
  {'name': 'rem', 'signatures': [['value']]},
  {'name': 'vw', 'signatures': [['value']]},
  {'name': 'vh', 'signatures': [['value']]},
  {'name': 'vmin', 'signatures': [['value']]},
  {'name': 'vmax', 'signatures': [['value']]},
  {'name': 'qw', 'signatures': [['value']]},
  {'name': 'qh', 'signatures': [['value']]},
  {'name': 'qi', 'signatures': [['value']]},
  {'name': 'qb', 'signatures': [['value']]},
  {'name': 'qmin', 'signatures': [['value']]},
  {'name': 'qmax', 'signatures': [['value']]},
  {'name': 'cm', 'signatures': [['value']]},
  {'name': 'mm', 'signatures': [['value']]},
  {'name': 'in', 'signatures': [['value']]},
  {'name': 'pt', 'signatures': [['value']]},
  {'name': 'pc', 'signatures': [['value']]},
  {'name': 'px', 'signatures': [['value']]},
  {'name': 'Q', 'signatures': [['value']]},
  {'name': 'deg', 'signatures': [['value']]},
  {'name': 'grad', 'signatures': [['value']]},
  {'name': 'rad', 'signatures': [['value']]},
  {'name': 'turn', 'signatures': [['value']]},
  {'name': 's', 'signatures': [['value']]},
  {'name': 'ms', 'signatures': [['value']]},
  {'name': 'Hz', 'signatures': [['value']]},
  {'name': 'kHz', 'signatures': [['value']]},
  {'name': 'dpi', 'signatures': [['value']]},
  {'name': 'dpcm', 'signatures': [['value']]},
  {'name': 'dppx', 'signatures': [['value']]},
  {'name': 'fr', 'signatures': [['value']]},
  {'name': 'CSSUnparsedValue', 'signatures': [['members']]},
  {'name': 'CSSVariableReferenceValue', 'signatures': [['variable', '?fallback']]},
  {'name': 'FontFaceSetLoadEvent', 'signatures': [['type', '?eventInitDict']]},
  {'name': 'FontFace', 'signatures': [['family', 'source', '?descriptors']]},
  {'name': 'MediaQueryListEvent', 'signatures': [['type', '?eventInitDict']]},
  {'name': 'registerProperty', 'signatures': [['definition']]},
  {'name': 'Comment', 'signatures': [['?data']]},
  {'name': 'DOMException', 'signatures': [['?message', '?name']]},
  {'name': 'CustomEvent', 'signatures': [['type', '?eventInitDict']]},
  {'name': 'Event', 'signatures': [['type', '?eventInitDict']]},
  {'name': 'MutationObserver', 'signatures': [['callback']]},
  {'name': 'StaticRange', 'signatures': [['init']]},
  {'name': 'Text', 'signatures': [['?data']]},
  {'name': 'CharacterBoundsUpdateEvent', 'signatures': [['?options']]},
  {'name': 'EditContext', 'signatures': [['?options']]},
  {'name': 'TextFormatUpdateEvent', 'signatures': [['?options']]},
  {'name': 'TextFormat', 'signatures': [['?options']]},
  {'name': 'TextUpdateEvent', 'signatures': [['?options']]},
  {'name': 'AnimationEvent', 'signatures': [['type', '?eventInitDict']]},
  {'name': 'AnimationPlaybackEvent', 'signatures': [['type', '?eventInitDict']]},
  {'name': 'ClipboardEvent', 'signatures': [['type', '?eventInitDict']]},
  {'name': 'CompositionEvent', 'signatures': [['type', '?eventInitDict']]},
  {'name': 'DragEvent', 'signatures': [['type', '?eventInitDict']]},
  {'name': 'ErrorEvent', 'signatures': [['type', '?eventInitDict']]},
  {'name': 'FocusEvent', 'signatures': [['type', '?eventInitDict']]},
  {'name': 'HashChangeEvent', 'signatures': [['type', '?eventInitDict']]},
  {'name': 'InputEvent', 'signatures': [['type', '?eventInitDict']]},
  {'name': 'KeyboardEvent', 'signatures': [['type', '?eventInitDict']]},
  {'name': 'MessageEvent', 'signatures': [['type', '?eventInitDict']]},
  {'name': 'MouseEvent', 'signatures': [['type', '?eventInitDict']]},
  {'name': 'OverscrollEvent', 'signatures': [['type', 'bubbles', '?eventInitDict']]},
  {'name': 'PageTransitionEvent', 'signatures': [['type', '?eventInitDict']]},
  {'name': 'PointerEvent', 'signatures': [['type', '?eventInitDict']]},
  {'name': 'PopStateEvent', 'signatures': [['type', '?eventInitDict']]},
  {'name': 'ProgressEvent', 'signatures': [['type', '?eventInitDict']]},
  {'name': 'PromiseRejectionEvent', 'signatures': [['type', 'eventInitDict']]},
  {'name': 'SecurityPolicyViolationEvent', 'signatures': [['type']]},
  {'name': 'TouchEvent', 'signatures': [['type', '?eventInitDict']]},
  {'name': 'TransitionEvent', 'signatures': [['type', '?eventInitDict']]},
  {'name': 'UIEvent', 'signatures': [['type', '?eventInitDict']]},
  {'name': 'WheelEvent', 'signatures': [['type', '?eventInitDict']]},
  {'name': 'Headers', 'signatures': [['?init']]},
  {'name': 'Request', 'signatures': [['input', '?init']]},
  {'name': 'Response', 'signatures': [['?body', '?init']]},
  {'name': 'Blob', 'signatures': [['?blobParts', '?options']]},
  {'name': 'File', 'signatures': [['fileBits', 'fileName', '?options']]},
  {'name': 'TextDirective', 'signatures': [['?options']]},
  {'name': 'ReportingObserver', 'signatures': [['callback', '?options']]},
  {'name': 'WindowControlsOverlayGeometryChangeEvent', 'signatures': [['type', 'eventInitDict']]},
  {'name': 'DOMMatrixReadOnly', 'signatures': [['?init']]},
  {'name': 'DOMMatrix', 'signatures': [['?init']]},
  {'name': 'DOMPointReadOnly', 'signatures': [['?x', '?y', '?z', '?w']]},
  {'name': 'DOMPoint', 'signatures': [['?x', '?y', '?z', '?w']]},
  {'name': 'DOMQuad', 'signatures': [['?p1', '?p2', '?p3', '?p4']]},
  {'name': 'DOMRectReadOnly', 'signatures': [['?x', '?y', '?width', '?height']]},
  {'name': 'DOMRect', 'signatures': [['?x', '?y', '?width', '?height']]},
  {'name': 'Highlight', 'signatures': [['...initRanges']]},
  {'name': 'ImageData', 'signatures': [['sw', 'sh']]},
  {'name': 'FormDataEvent', 'signatures': [['type', 'eventInitDict']]},
  {'name': 'FormData', 'signatures': [['?form']]},
  {'name': 'Option', 'signatures': [['?data', '?value', '?defaultSelected', '?selected']]},
  {'name': 'SubmitEvent', 'signatures': [['type', '?eventInitDict']]},
  {'name': 'Image', 'signatures': [['?width', '?height']]},
  {'name': 'Audio', 'signatures': [['?src']]},
  {'name': 'PortalActivateEvent', 'signatures': [['type', '?eventInitDict']]},
  {'name': 'TrackEvent', 'signatures': [['type', '?eventInitDict']]},
  {'name': 'VTTCue', 'signatures': [['startTime', 'endTime', 'text']]},
  {'name': 'InputDeviceCapabilities', 'signatures': [['?deviceInitDict']]},
  {'name': 'Touch', 'signatures': [['initDict']]},
  {'name': 'IntersectionObserver', 'signatures': [['callback', '?options']]},
  {'name': 'MojoInterfaceInterceptor', 'signatures': [['interfaceName', '?scope']]},
  {'name': 'MojoInterfaceRequestEvent', 'signatures': [['type', '?eventInitDict']]},
  {'name': 'OffscreenCanvas', 'signatures': [['width', 'height']]},
  {'name': 'ScrollState', 'signatures': [['?scrollStateInit']]},
  {'name': 'ResizeObserver', 'signatures': [['callback']]},
  {'name': 'ByteLengthQueuingStrategy', 'signatures': [['init']]},
  {'name': 'CountQueuingStrategy', 'signatures': [['init']]},
  {'name': 'ReadableStreamBYOBReader', 'signatures': [['stream']]},
  {'name': 'ReadableStreamDefaultReader', 'signatures': [['stream']]},
  {'name': 'ReadableStream', 'signatures': [['?underlyingSource', '?strategy']]},
  {'name': 'TransformStream', 'signatures': [['?transformer', '?writableStrategy', '?readableStrategy']]},
  {'name': 'WritableStream', 'signatures': [['?underlyingSink', '?strategy']]},
  {'name': 'PerformanceMark', 'signatures': [['markName', '?markOptions']]},
  {'name': 'PerformanceObserver', 'signatures': [['callback']]},
  {'name': 'Profiler', 'signatures': [['options']]},
  {'name': 'URLSearchParams', 'signatures': [['?init']]},
  {'name': 'URL', 'signatures': [['url', '?base']]},
  {'name': 'SharedWorker', 'signatures': [['scriptURL', '?options']]},
  {'name': 'Worker', 'signatures': [['scriptURL', '?options']]},
  {'name': 'WorkletAnimation', 'signatures': [['animatorName', 'effects', '?timeline', '?options']]},
  {'name': 'BeforeInstallPromptEvent', 'signatures': [['type', '?eventInitDict']]},
  {'name': 'BackgroundFetchEvent', 'signatures': [['type', 'init']]},
  {'name': 'BackgroundFetchUpdateUIEvent', 'signatures': [['type', 'init']]},
  {'name': 'PeriodicSyncEvent', 'signatures': [['type', 'init']]},
  {'name': 'SyncEvent', 'signatures': [['type', 'init']]},
  {'name': 'MediaStreamTrackGenerator', 'signatures': [['kind']]},
  {'name': 'MediaStreamTrackProcessor', 'signatures': [['track', '?bufferSize']]},
  {'name': 'BroadcastChannel', 'signatures': [['name']]},
  {'name': 'CanvasFilter', 'signatures': [['init']]},
  {'name': 'CanvasFormattedTextRun', 'signatures': [['text']]},
  {'name': 'Path2D', 'signatures': [['?path']]},
  {'name': 'ClipboardItem', 'signatures': [['items', '?options']]},
  {'name': 'CompressionStream', 'signatures': [['format']]},
  {'name': 'DecompressionStream', 'signatures': [['format']]},
  {'name': 'ComputePressureObserver', 'signatures': [['callback', '?options']]},
  {'name': 'ContentIndexEvent', 'signatures': [['type', 'init']]},
  {'name': 'FederatedCredential', 'signatures': [['data']]},
  {'name': 'PasswordCredential', 'signatures': [['data']]},
  {'name': 'DeviceMotionEvent', 'signatures': [['type', '?eventInitDict']]},
  {'name': 'DeviceOrientationEvent', 'signatures': [['type', '?eventInitDict']]},
  {'name': 'TextDecoderStream', 'signatures': [['?label', '?options']]},
  {'name': 'TextDecoder', 'signatures': [['?label', '?options']]},
  {'name': 'MediaEncryptedEvent', 'signatures': [['type', '?eventInitDict']]},
  {'name': 'MediaKeyMessageEvent', 'signatures': [['type', 'eventInitDict']]},
  {'name': 'EventSource', 'signatures': [['url', '?eventSourceInitDict']]},
  {'name': 'GamepadAxisEvent', 'signatures': [['type', '?eventInitDict']]},
  {'name': 'GamepadButtonEvent', 'signatures': [['type', '?eventInitDict']]},
  {'name': 'GamepadEvent', 'signatures': [['type', '?eventInitDict']]},
  {'name': 'HIDConnectionEvent', 'signatures': [['type', 'eventInitDict']]},
  {'name': 'ImageCapture', 'signatures': [['track']]},
  {'name': 'IDBVersionChangeEvent', 'signatures': [['type', '?eventInitDict']]},
  {'name': 'BlobEvent', 'signatures': [['type', 'eventInitDict']]},
  {'name': 'MediaRecorder', 'signatures': [['stream', '?options']]},
  {'name': 'MediaMetadata', 'signatures': [['?init']]},
  {'name': 'TrackDefaultList', 'signatures': [['?trackDefaults']]},
  {'name': 'TrackDefault', 'signatures': [['type', 'language', 'label', 'kinds', '?byteStreamTrackID']]},
  {'name': 'CaptureHandleChangeEvent', 'signatures': [['type', 'eventInitDict']]},
  {'name': 'MediaStreamEvent', 'signatures': [['type', '?eventInitDict']]},
  {'name': 'MediaStreamTrackEvent', 'signatures': [['type', 'eventInitDict']]},
  {'name': 'OverconstrainedError', 'signatures': [['constraint', 'message']]},
  {'name': 'NDEFMessage', 'signatures': [['messageInit']]},
  {'name': 'NDEFReadingEvent', 'signatures': [['type', 'eventInitDict']]},
  {'name': 'NDEFRecord', 'signatures': [['recordInit']]},
  {'name': 'NotificationEvent', 'signatures': [['type', 'eventInitDict']]},
  {'name': 'Notification', 'signatures': [['title', '?options']]},
  {'name': 'TimestampTrigger', 'signatures': [['timestamp']]},
  {'name': 'AbortPaymentEvent', 'signatures': [['type', 'eventInitDict']]},
  {'name': 'CanMakePaymentEvent', 'signatures': [['type', 'eventInitDict']]},
  {'name': 'MerchantValidationEvent', 'signatures': [['type', '?eventInitDict']]},
  {'name': 'PaymentMethodChangeEvent', 'signatures': [['type', '?eventInitDict']]},
  {'name': 'PaymentRequestEvent', 'signatures': [['type', 'eventInitDict']]},
  {'name': 'PaymentRequestUpdateEvent', 'signatures': [['type', '?eventInitDict']]},
  {'name': 'PaymentRequest', 'signatures': [['methodData', '?details', '?options']]},
  {'name': 'RTCDataChannelEvent', 'signatures': [['type', 'eventInitDict']]},
  {'name': 'RTCDTMFToneChangeEvent', 'signatures': [['type', 'eventInitDict']]},
  {'name': 'RTCErrorEvent', 'signatures': [['type', 'eventInitDict']]},
  {'name': 'RTCError', 'signatures': [['init', '?message']]},
  {'name': 'RTCIceCandidate', 'signatures': [['?candidateInitDict']]},
  {'name': 'RTCPeerConnectionIceErrorEvent', 'signatures': [['type', 'eventInitDict']]},
  {'name': 'RTCPeerConnectionIceEvent', 'signatures': [['type', '?eventInitDict']]},
  {'name': 'RTCPeerConnection', 'signatures': [['?configuration', '?mediaConstraints']]},
  {'name': 'RTCSessionDescription', 'signatures': [['?descriptionInitDict']]},
  {'name': 'PictureInPictureEvent', 'signatures': [['type', 'eventInitDict']]},
  {'name': 'PresentationConnectionAvailableEvent', 'signatures': [['type', 'eventInitDict']]},
  {'name': 'PresentationConnectionCloseEvent', 'signatures': [['type', 'eventInitDict']]},
  {'name': 'PresentationRequest', 'signatures': [['url']]},
  {'name': 'PushEvent', 'signatures': [['type', '?eventInitDict']]},
  {'name': 'PushSubscriptionChangeEvent', 'signatures': [['type', '?eventInitDict']]},
  {'name': 'DOMError', 'signatures': [['name', '?message']]},
  {'name': 'Sanitizer', 'signatures': [['?config']]},
  {'name': 'TaskController', 'signatures': [['?init']]},
  {'name': 'TaskPriorityChangeEvent', 'signatures': [['type', 'eventInitDict']]},
  {'name': 'AbsoluteOrientationSensor', 'signatures': [['?sensorOptions']]},
  {'name': 'Accelerometer', 'signatures': [['?sensorOptions']]},
  {'name': 'AmbientLightSensor', 'signatures': [['?sensorOptions']]},
  {'name': 'GravitySensor', 'signatures': [['?sensorOptions']]},
  {'name': 'Gyroscope', 'signatures': [['?sensorOptions']]},
  {'name': 'LinearAccelerationSensor', 'signatures': [['?sensorOptions']]},
  {'name': 'Magnetometer', 'signatures': [['?sensorOptions']]},
  {'name': 'RelativeOrientationSensor', 'signatures': [['?sensorOptions']]},
  {'name': 'SensorErrorEvent', 'signatures': [['type', 'eventInitDict']]},
  {'name': 'ExtendableEvent', 'signatures': [['type', '?eventInitDict']]},
  {'name': 'ExtendableMessageEvent', 'signatures': [['type', '?eventInitDict']]},
  {'name': 'FetchEvent', 'signatures': [['type', 'eventInitDict']]},
  {'name': 'InstallEvent', 'signatures': [['type', '?eventInitDict']]},
  {'name': 'BarcodeDetector', 'signatures': [['?barcodeDetectorOptions']]},
  {'name': 'FaceDetector', 'signatures': [['?faceDetectorOptions']]},
  {'name': 'SpeechSynthesisErrorEvent', 'signatures': [['type', 'eventInitDict']]},
  {'name': 'SpeechSynthesisEvent', 'signatures': [['type', 'eventInitDict']]},
  {'name': 'SpeechSynthesisUtterance', 'signatures': [['?text']]},
  {'name': 'StorageEvent', 'signatures': [['type', '?eventInitDict']]},
  {'name': 'URLPattern', 'signatures': [['?input', '?baseURL']]},
  {'name': 'VirtualKeyboardGeometryChangeEvent', 'signatures': [['type']]},
  {'name': 'AnalyserNode', 'signatures': [['context', '?options']]},
  {'name': 'AudioBufferSourceNode', 'signatures': [['context', '?options']]},
  {'name': 'AudioBuffer', 'signatures': [['options']]},
  {'name': 'AudioContext', 'signatures': [['?contextOptions']]},
  {'name': 'AudioProcessingEvent', 'signatures': [['type', 'eventInitDict']]},
  {'name': 'AudioWorkletNode', 'signatures': [['context', 'name', '?options']]},
  {'name': 'BiquadFilterNode', 'signatures': [['context', '?options']]},
  {'name': 'ChannelMergerNode', 'signatures': [['context', '?options']]},
  {'name': 'ChannelSplitterNode', 'signatures': [['context', '?options']]},
  {'name': 'ConstantSourceNode', 'signatures': [['context', '?options']]},
  {'name': 'ConvolverNode', 'signatures': [['context', '?options']]},
  {'name': 'DelayNode', 'signatures': [['context', '?options']]},
  {'name': 'DynamicsCompressorNode', 'signatures': [['context', '?options']]},
  {'name': 'GainNode', 'signatures': [['context', '?options']]},
  {'name': 'IIRFilterNode', 'signatures': [['context', 'options']]},
  {'name': 'MediaElementAudioSourceNode', 'signatures': [['context', 'options']]},
  {'name': 'MediaStreamAudioDestinationNode', 'signatures': [['context', '?options']]},
  {'name': 'MediaStreamAudioSourceNode', 'signatures': [['context', 'options']]},
  {'name': 'OfflineAudioCompletionEvent', 'signatures': [['type', 'eventInitDict']]},
  {'name': 'OfflineAudioContext', 'signatures': [['numberOfChannels', 'numberOfFrames', 'sampleRate']]},
  {'name': 'OscillatorNode', 'signatures': [['context', '?options']]},
  {'name': 'PannerNode', 'signatures': [['context', '?options']]},
  {'name': 'PeriodicWave', 'signatures': [['context', '?options']]},
  {'name': 'StereoPannerNode', 'signatures': [['context', '?options']]},
  {'name': 'WaveShaperNode', 'signatures': [['context', '?options']]},
  {'name': 'AudioData', 'signatures': [['init']]},
  {'name': 'AudioDecoder', 'signatures': [['init']]},
  {'name': 'AudioEncoder', 'signatures': [['init']]},
  {'name': 'EncodedAudioChunk', 'signatures': [['init']]},
  {'name': 'EncodedVideoChunk', 'signatures': [['init']]},
  {'name': 'ImageDecoder', 'signatures': [['init']]},
  {'name': 'VideoColorSpace', 'signatures': [['?init']]},
  {'name': 'VideoDecoder', 'signatures': [['init']]},
  {'name': 'VideoEncoder', 'signatures': [['init']]},
  {'name': 'VideoFrame', 'signatures': [['source', '?init']]},
  {'name': 'WebGLContextEvent', 'signatures': [['type', '?eventInit']]},
  {'name': 'GPUUncapturedErrorEvent', 'signatures': [['type', 'gpuUncapturedErrorEventInitDict']]},
  {'name': 'GPUValidationError', 'signatures': [['message']]},
  {'name': 'MIDIConnectionEvent', 'signatures': [['type', '?eventInitDict']]},
  {'name': 'MIDIMessageEvent', 'signatures': [['type', '?eventInitDict']]},
  {'name': 'CloseEvent', 'signatures': [['type', '?eventInitDict']]},
  {'name': 'WebSocketStream', 'signatures': [['url', '?options']]},
  {'name': 'WebSocket', 'signatures': [['url', '?protocols']]},
  {'name': 'WebTransportError', 'signatures': [['?init']]},
  {'name': 'WebTransport', 'signatures': [['url', '?options']]},
  {'name': 'USBAlternateInterface', 'signatures': [['deviceInterface', 'alternateSetting']]},
  {'name': 'USBConfiguration', 'signatures': [['device', 'configurationValue']]},
  {'name': 'USBConnectionEvent', 'signatures': [['type', 'eventInitDict']]},
  {'name': 'USBEndpoint', 'signatures': [['alternate', 'endpointNumber', 'direction']]},
  {'name': 'USBInTransferResult', 'signatures': [['status', '?data']]},
  {'name': 'USBInterface', 'signatures': [['configuration', 'interfaceNumber']]},
  {'name': 'USBIsochronousInTransferPacket', 'signatures': [['status', '?data']]},
  {'name': 'USBIsochronousInTransferResult', 'signatures': [['packets', '?data']]},
  {'name': 'USBIsochronousOutTransferPacket', 'signatures': [['status', '?bytesWritten']]},
  {'name': 'USBIsochronousOutTransferResult', 'signatures': [['packets']]},
  {'name': 'USBOutTransferResult', 'signatures': [['status', '?bytesWritten']]},
  {'name': 'XRInputSourceEvent', 'signatures': [['type', 'eventInitDict']]},
  {'name': 'XRInputSourcesChangeEvent', 'signatures': [['type', 'eventInitDict']]},
  {'name': 'XRRay', 'signatures': [['?origin', '?direction']]},
  {'name': 'XRReferenceSpaceEvent', 'signatures': [['type', 'eventInitDict']]},
  {'name': 'XRRigidTransform', 'signatures': [['?position', '?orientation']]},
  {'name': 'XRSessionEvent', 'signatures': [['type', 'eventInitDict']]},
  {'name': 'XRWebGLBinding', 'signatures': [['session', 'context']]},
  {'name': 'XRWebGLLayer', 'signatures': [['session', 'context', '?layerInit']]},
  {'name': 'assert', 'signatures': [['?condition', '...data']]},
  {'name': 'debug', 'signatures': [['...data']]},
  {'name': 'error', 'signatures': [['...data']]},
  {'name': 'info', 'signatures': [['...data']]},
  {'name': 'table', 'signatures': [['?tabularData', '?properties']]},
  {'name': 'trace', 'signatures': [['...data']]},
  {'name': 'warn', 'signatures': [['...data']]},
  {'name': 'dir', 'signatures': [['?item', '?options']]},
  {'name': 'dirxml', 'signatures': [['...data']]},
  {'name': 'count', 'signatures': [['?label']]},
  {'name': 'countReset', 'signatures': [['?label']]},
  {'name': 'group', 'signatures': [['...data']]},
  {'name': 'groupCollapsed', 'signatures': [['...data']]},
  {'name': 'time', 'signatures': [['?label']]},
  {'name': 'timeLog', 'signatures': [['?label', '...data']]},
  {'name': 'timeEnd', 'signatures': [['?label']]}
];
