// Copyright 2020 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

/* eslint-disable no-console */

// use require here due to
// https://github.com/evanw/esbuild/issues/587#issuecomment-901397213
import puppeteer = require('puppeteer-core');

import {type CoverageMapData} from 'istanbul-lib-coverage';

import {
  clearPuppeteerState,
  getBrowserAndPages,
  registerHandlers,
  setBrowserAndPages,
  setTestServerPort,
} from './puppeteer-state.js';
import {
  loadEmptyPageAndWaitForContent,
  DevToolsFrontendTab,
  type DevToolsFrontendReloadOptions,
} from './frontend_tab.js';
import {
  dumpCollectedErrors,
  installPageErrorHandlers,
  setupBrowserProcessIO,
} from './events.js';
import {TargetTab} from './target_tab.js';
import {TestConfig} from './test_config.js';

// Workaround for mismatching versions of puppeteer types and puppeteer library.
declare module 'puppeteer-core' {
  // eslint-disable-next-line @typescript-eslint/no-unused-vars
  interface ConsoleMessage {
    stackTrace(): ConsoleMessageLocation[];
  }
}

const viewportWidth = 1280;
const viewportHeight = 720;
// Adding some offset to the window size used in the headful mode
// so to account for the size of the browser UI.
// Values are choosen by trial and error to make sure that the window
// size is not much bigger than the viewport but so that the entire
// viewport is visible.
const windowWidth = viewportWidth + 50;
const windowHeight = viewportHeight + 200;

const headless = !TestConfig.debug;
const envSlowMo = process.env['STRESS'] ? 50 : undefined;
const envThrottleRate = process.env['STRESS'] ? 3 : 1;
const envLatePromises = process.env['LATE_PROMISES'] !== undefined ?
    ['true', ''].includes(process.env['LATE_PROMISES'].toLowerCase()) ? 10 : Number(process.env['LATE_PROMISES']) :
    0;

let browser: puppeteer.Browser;
let frontendTab: DevToolsFrontendTab;
let targetTab: TargetTab;

const envChromeFeatures = process.env['CHROME_FEATURES'];

export async function watchForHang<T>(
    currentTest: string|undefined, stepFn: (currentTest: string|undefined) => Promise<T>): Promise<T> {
  const stepName = stepFn.name || stepFn.toString();
  const stackTrace = new Error().stack;
  function logTime(label: string) {
    const end = performance.now();
    console.error(`\n${stepName} ${label} ${end - start}ms\nTrace: ${stackTrace}\nTest: ${currentTest}\n`);
  }
  let tripped = false;
  const timerId = setTimeout(() => {
    logTime('takes at least');
    tripped = true;
  }, 10000);
  const start = performance.now();
  try {
    const result = await stepFn(currentTest);
    if (tripped) {
      logTime('succeded after');
    }
    return result;
  } catch (err) {
    logTime('errored after');
    throw err;
  } finally {
    clearTimeout(timerId);
  }
}

function launchChrome() {
  // Use port 0 to request any free port.
  const enabledFeatures = [
    'Portals',
    'PortalsCrossOrigin',
    'PartitionedCookies',
    'SharedStorageAPI',
    'FencedFrames',
    'PrivacySandboxAdsAPIsOverride',
    'AutofillEnableDevtoolsIssues',
  ];
  const launchArgs = [
    '--remote-allow-origins=*',
    '--remote-debugging-port=0',
    '--enable-experimental-web-platform-features',
    // This fingerprint may be generated from the certificate using
    // openssl x509 -noout -pubkey -in scripts/hosted_mode/cert.pem | openssl pkey -pubin -outform der | openssl dgst -sha256 -binary | base64
    '--ignore-certificate-errors-spki-list=KLy6vv6synForXwI6lDIl+D3ZrMV6Y1EMTY6YpOcAos=',
    '--site-per-process',  // Default on Desktop anyway, but ensure that we always use out-of-process frames when we intend to.
    '--host-resolver-rules=MAP *.test 127.0.0.1',
    '--disable-gpu',
    '--enable-blink-features=CSSContainerQueries,HighlightInheritance',  // TODO(crbug.com/1218390) Remove globally enabled flags and conditionally enable them
    '--disable-blink-features=WebAssemblyJSPromiseIntegration',  // TODO(crbug.com/325123665) Remove once heap snapshots work again with JSPI
    '--enable-features="AblateSearchProviderWarmup<AblateSearchProviderWarmupRequests,AccessibilityPruneRedundantInlineText<PruneRedundantAXInlineTextBoxText,AccessibilitySerializationSizeMetrics<AccessibilitySerializationSizeMetrics,AckOnSurfaceActivationWhenInteractive<EnableImmediateDrawDuringScrollInteraction,ActiveContentSettingExpiry<OneTimePermission,AllowDatapipeDrainedAsBytesConsumerInBFCache<AllowDatapipeDrainedAsBytesConsumerInBFCache,AllowJavaScriptToResetAutofillState<AutofillFixCachingOnJavaScriptChanges,AnimationForDesktopCapturePermissionChecker<AnimationForDesktopCapturePermissionChecker,AsyncQuicSession<AsyncQuicSession,AttributionDebugReportingCookieDeprecationTesting<CookieDeprecationFacilitatedTestingCookieDeprecation,AttributionReportDeliveryRetryDelays<AttributionReportDeliveryRetryDelays,AudioRendererAlgorithmParameters<AudioRendererAlgorithmStartingCapacityForEncrypted,AutoDisableAccessibility<AutoDisableAccessibility,AutoSpeculationRules<AutoSpeculationRules,AutofillAddressFieldSwapping<AutofillAddressFieldSwapping,AutofillAddressUserPerceptionSurvey<AutofillAddressUserPerceptionSurveyUS,AutofillCardSurvey<AutofillSurveys,AutofillCaretExtraction<ComposeProactiveNudgePosition,AutofillChangeDisusedAddressSuggestionTreatment<AutofillChangeDisusedAddressSuggestionTreatment,AutofillConsiderPhoneNumberSeparatorsValidLabels<AutofillPhoneNumberDetectionImprovements,AutofillCreditCardUserPerceptionSurvey<AutofillCreditCardUserPerceptionSurvey,AutofillDontPrefixMatchCreditCardNumbersOrCvcs<AutofillDontPrefixMatchCreditCardNumbersOrCvcs,AutofillEnableAccountStorageForIneligibleCountries<AutofillEnableAccountStorageForIneligibleCountries,AutofillEnableCardBenefitsForAmericanExpress<AutofillEnableCardBenefits,AutofillEnableCardBenefitsForCapitalOne<AutofillEnableCardBenefits,AutofillEnableCvcStorageAndFilling<AutofillEnableCvcStorage,AutofillEnableDevtoolsIssues,AutofillEnableEmailHeuristicOnlyAddressForms<AutofillEnableEmailHeuristicOnlyAddressForms,AutofillEnableExpirationDateImprovements<AutofillEnableExpirationDateImprovements,AutofillEnableFillingPhoneCountryCodesByAddressCountryCodes<AutofillEnableFillingPhoneCountryCodesByAddressCountryCodes,AutofillEnableFpanRiskBasedAuthentication<AutofillEnableFpanRiskBasedAuthentication,AutofillEnableLabelPrecedenceForTurkishAddresses<AutofillEnableLabelPrecedenceForTurkishAddresses,AutofillEnableManualFallbackIPH<AutofillEnableManualFallbackIPH,AutofillEnableMerchantDomainInUnmaskCardRequest<AutofillEnableMerchantDomainInUnmaskCardRequest,AutofillEnableNewSaveCardBubbleUi<AutofillEnableNewSaveCardBubbleUi,AutofillEnablePaymentsFieldSwapping<AutofillEnablePaymentsFieldSwapping,AutofillEnableRankingFormulaAddressProfiles<AutofillEnableNewCardProfileRankingAlgorithm,AutofillEnableRankingFormulaCreditCards<AutofillEnableNewCardProfileRankingAlgorithm,AutofillEnableSaveCardLoadingAndConfirmation<AutofillEnableLoadingAndConfirmation,AutofillEnableSaveCardLocalSaveFallback<AutofillEnableLoadingAndConfirmation,AutofillEnableSupportForPhoneNumberTrunkTypes<AutofillPhoneNumberDetectionImprovements,AutofillEnableVcnEnrollLoadingAndConfirmation<AutofillEnableLoadingAndConfirmation,AutofillEnableVerveCardSupport<AutofillEnableVerveCardSupport,AutofillFixCachingOnJavaScriptChanges<AutofillFixCachingOnJavaScriptChanges,AutofillForUnclassifiedFieldsAvailable<AutofillForUnclassifiedFieldsAvailable,AutofillGranularFillingAvailable<AutofillGranularFillingAvailable,AutofillInferCountryCallingCode<AutofillPhoneNumberDetectionImprovements,AutofillLogDeduplicationMetrics<AutofillLogDeduplicationMetrics,AutofillLogUKMEventsWithSampleRate<AutofillLogUKMEventsWithSampleRate,AutofillModelPredictions<AutofillModelPredictions,AutofillMoreProminentPopup<AutofillMoreProminentPopup,AutofillOverwritePlaceholdersOnly<AutofillPreFilledFieldsCorrectly,AutofillParseVcnCardOnFileStandaloneCvcFields<AutofillEnableVirtualCardOnFile,AutofillPasswordUserPerceptionSurvey<AutofillPasswordUserPerceptionSurvey,AutofillPopupZOrderSecuritySurface<AutofillPopupZOrderSecuritySurface_V2,AutofillPreferParsedPhoneNumber<AutofillPhoneNumberDetectionImprovements,AutofillReplaceCachedWebElementsByRendererIds<AutofillImproveSubmissionDetection,AutofillRequireValidLocalCardsInSettings<AutofillRequireValidLocalCardsInSettings,AutofillSharedStorageServerCardData<AutofillSharedStorageServerCardData,AutofillSilentlyRemoveQuasiDuplicates<AutofillSilentlyRemoveQuasiDuplicates,AutofillSkipPreFilledFields<AutofillPreFilledFieldsCorrectly,AutofillStructuredFieldsDisableAddressLines<AutofillStructuredFieldsDisableAddressLines,AutofillSuggestionNStrikeModel<AutofillSuggestionNStrikeModel,AutofillUKMExperimentalFields<AutofillUKMExperimentalFields,AutofillUnifyAndFixFormTracking<AutofillImproveSubmissionDetection,AutofillUploadCardRequestTimeout<AutofillUploadCardRequestTimeout,AutofillUploadVotesForFieldsWithEmail<AutofillUploadVotesForFieldsWithEmail,AutofillUpstream<AutofillUpstream,AutofillUpstreamUpdatedUi<AutofillUpstreamUpdatedUi,AutofillUseAUAddressModel<AutofillI18nAddressModelNewCountries,AutofillUseCAAddressModel<AutofillI18nAddressModelNewCountries,AutofillUseDEAddressModel<AutofillI18nAddressModelNewCountries,AutofillUsePLAddressModel<AutofillI18nAddressModelNewCountries,AutofillVcnEnrollRequestTimeout<AutofillVcnEnrollRequestTimeout,AvoidEntryCreationForNoStore<AvoidEntryCreationForNoStore,AvoidLoadingPredictorPrefetchDuringBrowserStartup<AvoidLoadingPredictorPrefetchDuringBrowserStartup,AvoidResourceRequestCopies<AvoidResourceRequestCopies,AvoidScheduleWorkDuringNativeEventProcessing<AvoidScheduleWorkDuringNativeEventProcessing,BackForwardCacheMediaSessionService<BackForwardCacheMediaSessionService,BackForwardCacheSendNotRestoredReasons<BackForwardCacheNotRestoredReasons,BackgroundResourceFetch<BackgroundResourceFetch,BatchNativeEventsInMessagePumpKqueue<BatchNativeEventsInMessagePumpKqueue,BatterySaverModeAlignWakeUps<BatterySaverModeAlignWakeUps,BatterySaverModeRenderTuning<BatterySaverModeRenderTuning,BeforeunloadEventCancelByPreventDefault<BeforeunloadEventCancelByPreventDefault,BlockAcceptClientHints<BlockAcceptClientHints,BlockInsecurePrivateNetworkRequests,BlockInsecurePrivateNetworkRequestsFromPrivate,BlockInsecurePrivateNetworkRequestsFromUnknown,BookmarkTriggerForPrerender2<Prerender2BookmarkBarTrigger,BoostRenderProcessForLoading<BoostRenderProcessForLoading,BoundaryEventDispatchTracksNodeRemoval<BoundaryEventDispatchTracksNodeRemoval,BrowserSwitcherNoneIsGreylist<BrowserSwitcherNoneIsGreylist,BrowserThreadPoolAdjustment<BrowserThreadPoolAdjustmentForDesktop,BubbleMetricsApi<BubbleMetricsApi,BufferSizeForFilterSourceStreamFeature<BufferSizeForFilterSourceStream,CPUInterventionEvaluationLogging<CPUInterventionEvaluationLogging,CPUMeasurementInFreezingPolicy<CPUMeasurementInFreezingPolicy,CSSDisplayAnimation<CSSDisplayAnimation,CSSDisplayModePictureInPicture,CSSLazyParsingFastPath<CSSLazyParsingFastPath,CVDisplayLinkBeginFrameSource<CVDisplayLinkBeginFrameSource,CacheControlNoStoreEnterBackForwardCache<BackForwardCacheForPageWithCacheControlNotStoredHeader,CacheMacSandboxProfiles<CatanCombinedHoldback23H2,CameraMicPreview<CameraMicPreview,Canvas2DAutoFlushParams<Canvas2DAutoFlushParams,Canvas2DHibernation<CanvasHibernationExperiments,Canvas2DHibernationReleaseTransferMemory<CanvasHibernationExperiments,Canvas2DReclaimUnusedResources<Canvas2DReclaimUnusedResources,CanvasHibernationSnapshotZstd<CanvasHibernationSnapshotZstd,CanvasOopRasterization<CanvasOutOfProcessRasterization,CastStreamingVp9<CastStreamingVp9,CbdTimeframeRequired<CbdTimeframeRequired,ChangeFrameRateOfLoadingTabAnimation<ChangeFrameRateOfLoadingTabAnimation,CheckHTMLParserBudgetLessOften<CheckHTMLParserBudgetLessOften,ChromeCartDomBasedHeuristics<ChromeCartDomBasedHeuristics,ChromeLabs<ChromeLabs,ChromeWideEchoCancellation<ChromeWideEchoCancellation,ClassifyUrlOnProcessResponseEvent<ClassifyUrlOnProcessResponseEvent,ClearCanvasResourcesInBackground<CanvasHibernationExperiments,ClearGrShaderDiskCacheOnInvalidPrefix<ClearGrShaderDiskCacheOnInvalidPrefix,ClearUndecryptablePasswords<ClearUndecryptablePasswords,ClientHintsFormFactors,ClientSideDetectionKeyboardPointerLockRequest<ClientSideDetectionKeyboardPointerLockRequest,ClientSideDetectionNotificationPrompt<ClientSideDetectionNotificationPrompt,ClientSideDetectionRetryLimit<ClientSideDetectionRetryLimit,ClientSideDetectionSamplePing<ClientSideDetectionSamplePing,ClientSideDetectionVibrationApi<ClientSideDetectionVibrationApi,CoalesceSelectionchangeEvent<CoalesceSelectionchangeEvent,CoalesceStorageAreaCommits<DOMStorageReliabilityEnhancements,CodeBasedRBD<CodeBasedRBD,CommerceLocalPDPDetection<CommerceLocalPDPDetection,Compose<ChromeCompose,ComposeProactiveNudge<ComposeProactiveNudgePosition,ComposeUiRefinement<ComposeUiRefinement,CompressionDictionaryTransport<CompressionDictionaryTransport,CompressionDictionaryTransportOverHttp1<CompressionDictionaryTransportOverHttp1,ConcurrentViewTransitionsSPA<ConcurrentViewTransitionsSPA,ConditionalImageResize<ConditionalImageResize,ConditionallySkipGpuChannelFlush<ConditionallySkipGpuChannelFlush,ConfigurableV8CodeCacheHotHours<ConfigurableV8CodeCacheHotHours,ContinueEventTimingRecordingWhenBufferIsFull<ContinueEventTimingRecordingWhenBufferIsFull,CookieAccessDetailsNotificationDeDuping<CookieAccessDetailsNotificationDeDuping,CookieDeprecationFacilitatedTesting<CookieDeprecationFacilitatedTestingCookieDeprecation,CookieSameSiteConsidersRedirectChain,Cr2023ActionChips<OmniboxCr23M113Desktop,Cr2023ActionChipsIcons<OmniboxCr23M113Desktop,CrabbyAvif<CrabbyAvif,CreateImageBitmapOrientationNone,CriticalClientHint,CssRubyAlign<CssRubyAlign,CustomizeChromeSidePanelExtensionsCard<CustomizeChromeSidePanelExtensionsCard,CustomizeChromeWallpaperSearch<ChromeWallpaperSearchGlobal,CustomizeChromeWallpaperSearchButton<ChromeWallpaperSearchEntrypoints,CustomizeChromeWallpaperSearchInspirationCard<ChromeWallpaperSearchGlobal,DIPS<DIPSStatefulBounceEnforcement,DTCKeyUploadedBySharedAPIEnabled<DTCKeyUploadedBySharedAPIEnabled,DangerousDownloadInterstitial<DangerousDownloadInterstitial,DecommitPooledPages<DecommitPooledPages,DecreaseProcessingAudioFifoSize<DecreaseProcessingAudioFifoSize,DedicatedWorkerAblationStudyEnabled<PlzDedicatedWorker,DefaultANGLEMetal<DefaultANGLEMetal,DefaultBrowserPromptRefresh<DefaultBrowserPromptRefreshMacLaunch,DefaultBrowserPromptRefreshTrial<DefaultBrowserPromptRefreshMacLaunch,DefaultGpuDiskCacheSize<DefaultGpuDiskCacheSize,DefaultOpenSSLBufferSizeFeature<DefaultOpenSSLBufferSizeFeature,DeferSpeculativeRFHCreation<DeferSpeculativeRFHCreation,DeferredSpareRendererForTopChromeWebUI<DeferredSparerRendererForTopChromeWebUI,DelayFirstPeriodicPAPurgeOrReclaim<CatanCombinedHoldback23H2,DelayFirstWorkerWake<CatanCombinedHoldback23H2,DelayMediaSinkDiscovery<DelayMediaSinkDiscovery,DelayParkingImages<ParkableImages,DelayablePriorityThresholdFeature<DelayablePriorityThreshold,DeleteStaleLocalStorageOnStartup<StaleStorageCleanup,DeleteStaleSessionCookiesOnStartup<StaleStorageCleanup,DeprecateUnload<DeprecateUnload,DeprecateUnloadByAllowList<DeprecateUnload,DesktopCapturePermissionChecker<DesktopCapturePermissionChecker,DesktopPWAsLinkCapturing<DesktopLinkCapturingPWAExperiment,DesktopScreenshots<SharingHubDesktopScreenshots,DestroySystemProfiles<DestroySystemProfiles,DetailsStyling<DetailsStyling,DetectHiDpiForMsaa<MsaaSettingsMac,DevToolsTabTarget<DevToolsTabTarget,DialogCustomRuleMessageEnabled<WebProtectCustomRuleMessageDialog,DisableQuotaDbFullFSync<QuotaDatabaseDisableFullFSync,DisallowManagedProfileSignout<DisallowManagedProfileSignout,DiscardInputEventsToRecentlyMovedFrames<DiscardInputEventsToRecentlyMovedFrames,DiscountConsentV2<DiscountConsentV2,DiscountDialogAutoPopupBehaviorSetting<DiscountAutoPopup,DlpRegionalizedEndpoints<DlpRegionalizedEndpoints,DoNotEvictOnAXLocationChange<DoNotEvictOnAXLocationChange,DocumentPictureInPictureAPI,DocumentPolicyIncludeJSCallStacksInCrashReports,DocumentPolicyNegotiation,DocumentReporting,DomStorageSmartFlushing<DOMStorageReliabilityEnhancements,DontAlwaysPushPictureLayerImpls<DontAlwaysPushPictureLayerImpls,DownloadWarningSurvey<DownloadWarningSurvey,DrawImmediatelyWhenInteractive<EnableImmediateDrawDuringScrollInteraction,DropUnrecognizedTemplateUrlParameters<DropUnrecognizedTemplateUrlParameters,DynamicScrollCullRectExpansion<DynamicScrollCullRectExpansion,EarlyEstablishGpuChannel<EstablishGpuChannelChanges,EnableBackForwardCacheForOngoingSubframeNavigation<EnableBackForwardCacheForOngoingSubframeNavigation,EnableCanvas2DLayers,EnableComposeNudgeAtCursor<ComposeProactiveNudgePosition,EnableConfigurableThreadCacheMinCachedMemoryForPurging<ThreadCacheMinCachedMemoryForPurging,EnableConfigurableThreadCacheMultiplier<EnableConfigurableThreadCacheMultiplier,EnableConfigurableThreadCachePurgeInterval<ThreadCachePurgeInterval,EnableDesktopDataControls<DataControlsDesktop,EnableExtensibleEnterpriseSSO<EnableExtensibleEnterpriseSSO,EnableExtensionsPermissionsForSupervisedUsersOnDesktop<ExtensionParentalControlsOnLinuxMacWindows,EnableFingerprintingProtectionFilter<FingerprintingProtectionFilter,EnableIpPrivacyProxy<IPProtectionPhase0,EnableOopPrintDrivers<OutOfProcessPrintDriversPrint,EnableOverwritingPlaceholderUsernames<EnableOverwritingPlaceholderUsernames,EnablePreferencesAccountStorage<EnablePreferencesAccountStorage,EnableScreenshotProtection<DataControlsScreenshotProtection,EnableSupervisedUserSkipParentApprovalToInstallExtensions<ExtensionParentalControlsOnLinuxMacWindows,EnableWatchdogReportOnlyModeOnGpuInit<EnableWatchdogReportOnlyModeOnGpuInit,EnsureExistingRendererAlive<EnsureExistingRendererAlive,EsbDownloadRowPromo<ESBDownloadRowPromo,EstablishGpuChannelAsync<EstablishGpuChannelChanges,EventTimingHandleKeyboardEventSimulatedClick<EventTimingHandleKeyboardEventSimulatedClick,EventTimingHandleOrphanPointerup<EventTimingHandleOrphanPointerup,EvictStaleQuotaStorage<StaleStorageCleanup,EvictionThrottlesDraw<EvictionThrottlesDraw,EvictionUnlocksResources<CanvasHibernationExperiments,ExcludeTransparentTextsFromBeingLcpEligible<ExcludeTransparentTextsFromBeingLcpEligible,ExperimentalContentSecurityPolicyFeatures,ExplicitBrowserSigninUIOnDesktop<UnoDesktopM0Full,ExtensionManifestV2Disabled<ExtensionManifestV2Deprecation,ExtensionsServiceWorkerOptimizedEventDispatch<ExtensionsServiceWorkerOptimizedEventDispatch,ExtractRelatedSearchesFromPrefetchedZPSResponse<RelatedSearchesViaZPSPrefetchingDesktop,ExtremeLightweightUAFDetector<ExtremeLightweightUAFDetector,FencedFrames,FencedFramesAutomaticBeaconCredentials<FencedFramesEnableCredentialsForAutomaticBeacons,FencedFramesCrossOriginAutomaticBeacons<FencedFramesEnableCrossOriginAutomaticBeacons,FencedFramesCrossOriginEventReportingUnlabeledTraffic<FencedFramesEnableCrossOriginEventReporting,FencedFramesM120FeaturesPart2<FencedFramesEnableM120Features,FencedFramesReportEventHeaderChanges<FencedFramesEnableReportEventHeaderChanges,FencedFramesSrcPermissionsPolicy<FencedFramesEnableSrcPermissionsPolicy,FetchLaterAPI<FetchLaterAPI,FetchListFamilyMembersWithCapability<FamilyMemberRoleFeedback,FledgeBidderWorkletGroupByOriginContextsToKeep<ProtectedAudienceMoreGroupByOriginContextsStudy,FledgeBidderWorkletThreadPool<ProtectedAudienceMultiThreadedBidderWorklet,FledgeBiddingAndAuctionServer<FLEDGEBiddingAndAuctionServer,FledgeConsiderKAnonymity<ProtectedAudiencesKAnonymityEnforcementStudy,FledgeDirectFromSellerSignalsHeaderAdSlot<ProtectedAudiencesHeaderDirectFromSellerSignalsStudy,FledgeEnableWALForInterestGroupStorage<PerfCombined2024,FledgeEnforceKAnonymity<ProtectedAudiencesKAnonymityEnforcementStudy,FledgeFacilitatedTestingSignalsHeaders<CookieDeprecationFacilitatedTestingFledgeTrustedSignalsHeaders,FledgePermitCrossOriginTrustedSignals<ProtectedAudiencesPermitCrossOriginTrustedSignals,FledgeRealTimeReporting<ProtectedAudiencesRealTimeReporting,FledgeSellerWorkletThreadPool<ProtectedAudienceMultiThreadedSellerWorklet,FlushPersistentSystemProfileOnWrite<FlushPersistentSystemProfileOnWrite,ForceSafeSearchForUnauthenticatedSupervisedUsers<KidsProfile,FormControlsVerticalWritingModeDirectionSupport<FormControlsVerticalWritingModeDirectionSupport,FrameRoutingCache<FrameRoutingCache,GenGpuDiskCacheKeyPrefixInGpuService<GenGpuDiskCacheKeyPrefixInGpuService,GenericFontSettingCache<GenericFontSettingCache,GetTheMostOutOfChrome<GetTheMostOutOfChrome,GetUserMediaDeferredDeviceSettingsSelection<CameraMicPreview,GlobalMediaControlsUpdatedUI<GlobalMediaControlsUpdatedUI,GrCacheLimitsFeature<GrCacheLimits,GwpAsanMalloc<GwpAsanDesktop2024,GwpAsanPartitionAlloc<GwpAsanDesktop2024,HangoutsExtensionV3<HangoutsExtensionV3,HappinessTrackingSurveysExtensionsSafetyHub<ExtensionPageHats,HappinessTrackingSurveysForDesktopM1AdPrivacyPage<PrivacySandboxHatsForDesktopM1,HappinessTrackingSurveysForDesktopPrivacyGuide<PrivacyGuideHats,HappinessTrackingSurveysForWallpaperSearch<ChromeWallpaperSearchHaTS,HappinessTrackingSurveysGetMostChrome<GetMostChromeHats,HeapProfilerCentralControl<HeapProfilingCentralControl,HeapProfilerReporting<HeapProfilingCentralControl,HideDelegatedFrameHostMac<HideDelegatedFrameHostMac,HideGuestModeForSupervisedUsers<KidsProfile,HistoryEmbeddings<HistoryEmbeddings,HitTestOpaqueness<HitTestOpaqueness,Http2Grease<HTTP2,HttpDiskCachePrewarming<HttpDiskCachePrewarming,HttpsFirstModeIncognito<HttpsFirstModeIncognitoPhase1,HttpsFirstModeV2ForEngagedSites<HttpsUpgrades,HttpsFirstModeV2ForTypicallySecureUsers<HttpsFirstModeV2ForTypicallySecureUsers,IPH_BackNavigationMenu<BackNavigationMenuIPH,IPH_DesktopSharedHighlighting<SharedHighlightingIphDesktop,IPH_PerformanceInterventionDialogFeature<PerformanceInterventionMetricsStudy,IPH_PriceInsightsPageActionIconLabelFeature<CommercePriceInsights,IPH_PriceTrackingPageActionIconLabelFeature<PriceTrackingPageActionIconLabelFeatureIPH,IPH_ReadingModeSidePanel<ReadAnythingIPHRollout,IPH_SidePanelGenericMenuFeature<SidePanelPinningWithResponsiveToolbar,IPH_SidePanelGenericPinnableFeature<SidePanelPinningWithResponsiveToolbar,IPH_SideSearch<SideSearchInProductHelp,IPH_TabAudioMuting<TabAudioMuting,IPH_TabSearch<TabSearchInProductHelp,ImageDecodeConfigurableFeature<DecodedImageWorkingSetBudget,ImageDescriptionsAlternativeRouting<ImageDescriptionsAlternativeRouting,ImmersiveFullscreen<MacImmersiveFullscreen,ImprovedSemanticsActivityIndicators<ImprovedSemanticsActivityIndicators,IncludeJSCallStackInExtensionApiRequest<IncludeJSCallStackInExtensionApiRequestStudy,IncreaseCoookieAccesCacheSize<IncreaseCoookieAccesCacheSize,IncreasedCmdBufferParseSlice<IncreasedCmdBufferParseSlice,IncrementLocalSurfaceIdForMainframeSameDocNavigation<IncrementLocalSurfaceIdForMainframeSameDocNavigation,IndexedDBCompressValuesWithSnappy<IndexedDBCompressValuesWithSnappy,InfoBarIconMonochrome<InfoBarIconMonochrome,InhibitLoadingStateUpdate<CatanCombinedHoldback23H2,InterestGroupUpdateIfOlderThan<ProtectedAudiencesUpdateIfOlderThanMs,IntersectionOptimization<IntersectionOptimization,IsolateFencedFrames<ProcessIsolationForFencedFrames,JourneysOmniboxHistoryClusterProvider<DesktopOmniboxShortcutBoost,JourneysOnDeviceClusteringContentClustering<JourneysOnDeviceClusteringContentClustering,KeepAliveInBrowserMigration<KeepAliveInBrowserMigration,KeyboardFocusableScrollers<KeyboardFocusableScrollers,LCPCriticalPathPredictor<LCPPImageLoadingPriority,LCPPAutoPreconnectLcpOrigin<FenderAutoPreconnectLcpOrigins,LCPPDeferUnusedPreload<LCPPDeferUnusedPreload,LCPPFontURLPredictor<LCPPFontURLPredictor,LCPPInitiatorOrigin<LCPPDoubleKey,LCPPLazyLoadImagePreload<LCPPLazyLoadImagePreload,LCPPMultipleKey<LCPPMultipleKey,LCPTimingPredictorPrerender2<LCPTimingPredictorPrerender2,LargerDataPipeAllocationSizeFeature<MojoLargerDataPipeAllocationSize,LayoutNGShapeCache<LayoutNGShapeCache,LazyBlinkTimezoneInit<LazyBlinkTimezoneInit,LeakSkiaEventTracerAtExit<LeakSkiaEventTracerAtExit,LeftHandSideActivityIndicators<LeftHandSideActivityIndicators,LensEnableImageTranslate<GoogleLensDesktopContentMenuTranslate,LensImageFormatOptimizations<GoogleLensDesktopImageFormatOptimizations,LensOverlay<Chromnient,LensStandalone<GoogleLensDesktopImageFormatOptimizations,LessAggressiveParkableString<ParkableStringExperiments,LevelDBProtoAsyncWrite<LevelDBProtoAsyncWrite,LinkPreview<LinkPreview,LinkedServicesSetting<LinkedServicesSetting,LinkedServicesSettingIos<LinkedServicesSetting,LiveCaptionExperimentalLanguages<LiveCaptionExperimentalLanguages,LiveCaptionMultiLanguage<LiveCaptionMultiLanguageRollout,LoadingPhaseBufferTimeAfterFirstMeaningfulPaint<LoadingPhaseBufferTimeAfterFirstMeaningfulPaint,LoadingPredictorLimitPreconnectSocketCount<LoadingPredictorLimitPreconnectSocketCount,LoadingPredictorPrefetch<ReactivePrefetchDesktop,LoadingPredictorUseOptimizationGuide<ReactivePrefetchDesktop,LocalStateEnterprisePasswordHashes<LocalStateEnterprisePasswordHashes,LogOnDeviceMetricsOnStartup<LogOnDeviceMetricsOnStartup,LogUrlScoringSignals<OmniboxLogURLScoringSignals,LowLatencyVideoRendererAlgorithm<WebRTC-ZeroPlayoutDelay,LowPriorityAsyncScriptExecution<LowPriorityAsyncScriptExecution,LowerHighResolutionTimerThreshold<BatterySaverModeAlignWakeUps,MacAllowBackgroundingRenderProcesses<MacAllowBackgroundingRenderProcesses,MacAppCodeSignClone<MacAppCodeSignSafeUpdates,MacEfficientFileFlush<PerfCombined2024,MacSetDefaultTaskRole<CatanCombinedHoldback23H2,MacWebContentsOcclusion<MacWebContentsOcclusionV2,MainThreadCompositingPriority<CatanCombinedHoldback23H2,MaskedDomainList<IPProtectionPhase0,MaxNumDelayableRequestsPerHostPerClientFeature<MaxNumDelayableRequestsPerHostPerClient,MediaDeviceIdPartitioning<MediaDeviceIdStoragePartitioning,MediaDeviceIdRandomSaltsPerStorageKey<MediaDeviceIdStoragePartitioning,MediaRecorderUseMediaVideoEncoder<MediaRecorderUseMediaVideoEncoder,MemoryCacheStrongReference<MemoryCacheStrongReference,MemoryCacheStrongReferenceFilterImages<MemoryCacheStrongReference,MemoryPurgeInBackground<MemoryPurgeInBackground,MetricsLogTrimming<MetricsLogTrimming,MetricsServiceDeltaSnapshotInBg<MetricsServiceDeltaSnapshotInBg,MigrateDefaultChromeAppToWebAppsGSuite<MigrateDefaultChromeAppToWebAppsGSuite,MigrateDefaultChromeAppToWebAppsNonGSuite<MigrateDefaultChromeAppToWebAppsNonGSuite,MlUrlPiecewiseMappedSearchBlending<OmniboxMlUrlPiecewiseMappedScoringDesktop,MlUrlScoring<OmniboxMlUrlPiecewiseMappedScoringDesktop,ModelQualityLogging<ComposeModelQualityLogging,MojoBindingsInlineSLS<PerfCombined2024,MojoChannelAssociatedCrashesOnSendError<MojoChannelAssociatedCrashesOnSendError,MojoChannelAssociatedSendUsesRunOrPostTask<MojoChannelAssociatedSendUsesRunOrPostTask,MojoInlineMessagePayloads<MojoInlineMessagePayloads,MojoPredictiveAllocation<MojoPredictiveAllocation,MouseDragOnCancelledMouseMove<MouseDragOnCancelledMouseMove,MutationEventsSpecialTrialMessage<MutationEventsSpecialTrialMessage,NetAdapterMaxBufSizeFeature<NetAdapterMaxBufSize,NetworkQualityEstimator<NetworkQualityEstimatorParameterTuning,NewEvSignalsEnabled<NewEvSignalsEnabled,NewTabPageTriggerForPrerender2<Prerender2NewTabPageTrigger,NoPasswordSuggestionFiltering<NoPasswordSuggestionFiltering,NoThrottlingVisibleAgent<NoThrottlingVisibleAgent,NormalMaxItemsInCacheForSoftwareFeature<NormalMaxItemsInCacheForSoftware,NotReachedIsFatal<NotReachedIsFatal,NtpBackgroundImageErrorDetection<DesktopNtpImageErrorDetection,NtpCalendarModule<DesktopNtpCalendar,NtpDriveModule<DesktopNtpDriveCache,NtpMiddleSlotPromoDismissal<DesktopNtpMiddleSlotPromoDismissal,NtpModulesLoadTimeoutMilliseconds<DesktopNtpModules,NtpMostRelevantTabResumptionModule<DesktopNtpTabResumption,NtpPhotosModule<DesktopNtpModules,NtpWallpaperSearchButton<ChromeWallpaperSearchEntrypoints,NtpWallpaperSearchButtonAnimation<ChromeWallpaperSearchEntrypoints,NumberOfCoresWithCpuSecurityMitigation<PerfCombined2024,OidcAuthProfileManagement<OidcAuthProfileManagement,OmniboxCalcProvider<DesktopOmniboxCalculatorProvider,OmniboxDocumentProviderNoSyncRequirement<OmniboxRelaxedDriveRequirements,OmniboxDomainSuggestions<DesktopOmnibox_HistoryQuickProviderSpecificity,OmniboxExpandedLayout<OmniboxCr23M113Desktop,OmniboxExpandedStateColors<OmniboxCr23M113Desktop,OmniboxExpandedStateHeight<OmniboxCr23M113Desktop,OmniboxExpandedStateShape<OmniboxCr23M113Desktop,OmniboxExpandedStateSuggestIcons<OmniboxCr23M113Desktop,OmniboxOnDeviceHeadProviderNonIncognito<OmniboxOnDeviceHeadModelSelectionFix,OmniboxOnDeviceTailModel<OmniboxOnDeviceTailSuggest,OmniboxRemoveSuggestionsFromClipboard<OmniboxBundledExperimentV1,OmniboxShortcutBoost<DesktopOmniboxShortcutBoost,OmniboxSteadyStateBackgroundColor<OmniboxCr23M113Desktop,OmniboxSteadyStateHeight<OmniboxCr23M113Desktop,OmniboxSteadyStateTextColor<OmniboxCr23M113Desktop,OmniboxSuggestionHoverFillShape<OmniboxCr23M113Desktop,OmniboxUIExperimentMaxAutocompleteMatches<OmniboxBundledExperimentV1,OmniboxVitalizeAutocompletedKeywords<DesktopOmniboxKeywordProvider,OneCopyLegacyMPVideoFrameUploadViaSI<OneCopyLegacyMPVideoFrameUploadViaSI,OneTimePermission<OneTimePermission,OptimizationGuideComposeOnDeviceEval<ComposeOnDeviceModel,OptimizationGuideOnDeviceModel<ComposeOnDeviceModel,OptimizationHintsFetchingSRP<OptGuideBatchSRPTuning,OptimizeLoadingDataUrls<SimplifyLoadingTransparentPlaceholderImage,OptimizeParsingDataUrls<OptimizeParsingDataUrls,OriginIsolationHeader,OutlineSilhouetteIcon<UnoDesktopM0Followup,PMProcessPriorityPolicy<PMProcessPriorityPolicy,PageInfoAboutThisSiteMoreLangs<PageInfoAboutThisSite40Langs,PaintCacheBudgetConfigurableFeature<PaintCacheBudget,PaintHoldingForIframes<PaintHoldingOOPIF,ParkableImagesToDisk<ParkableImages,PartitionAllocBackupRefPtr<PartitionAllocBackupRefPtr,PartitionAllocLargeThreadCacheSize<PartitionAllocLargeThreadCacheSizeDesktop,PartitionAllocMakeFreeNoOpOnShutdown<PartitionAllocMakeFreeNoOpOnShutdown,PartitionAllocMemoryReclaimer<PartitionAllocMemoryReclaimer,PartitionAllocSchedulerLoopQuarantine<PartitionAllocAdvancedMemorySafetyChecks,PartitionAllocShortMemoryReclaim<PartitionAllocShortMemoryReclaim,PartitionAllocSortSmallerSlotSpanFreeLists<PartitionAllocMemoryReclaimer,PartitionAllocStraightenLargerSlotSpanFreeLists<PartitionAllocMemoryReclaimer,PartitionAllocUnretainedDanglingPtr<PartitionAllocUnretainedDanglingPtr,PartitionAllocUsePoolOffsetFreelists<PartitionAllocUsePoolOffsetFreelists,PartitionAllocUseSmallSingleSlotSpans<PartitionAllocUseSmallSingleSlotSpans,PartitionAllocZappingByFreeFlags<PartitionAllocAdvancedMemorySafetyChecks,PartitionConnectionsByNetworkIsolationKey<PartitionNetworkStateByNetworkAnonymizationKey,PartitionVisitedLinkDatabase<PartitionVisitedLinkDatabase,PartitionedCookies,PassHistogramSharedMemoryOnLaunch<PassHistogramSharedMemoryOnLaunch,PasswordGenerationExperiment<PasswordGenerationExperiment,PasswordStrongLabel<PasswordGenerationExperiment,Path2DPaintCache<Path2DPaintCache,PdfOcr<PdfOcrDesktop,PdfOopif,PdfUseSkiaRenderer<PdfUseSkiaRenderer,PerformanceControlsHighEfficiencyOptOutSurvey<PerformanceControlsHatsStudy,PerformanceIntervention<PerformanceInterventionMetricsStudy,PerformanceInterventionUI<PerformanceInterventionUI,PermissionElementPromptPositioning<PermissionElementPromptPositioning,PermissionsPromptSurvey<PermissionsPEPCHaTS,PlusAddressAffiliations<PlusAddressesExperiment,PlusAddressFallbackFromContextMenu<PlusAddressesExperiment,PlusAddressOfferCreationOnSingleUsernameForms<PlusAddressesExperiment,PlusAddressRefresh<PlusAddressesExperiment,PlusAddressSettingsRefreshDesktop<PlusAddressesExperiment,PlusAddressesEnabled<PlusAddressesExperiment,PlzDedicatedWorker<PlzDedicatedWorker,Portals,PortalsCrossOrigin,PowerBookmarkBackend<PowerBookmarkBackend,PreInitializePageAndFrameForSVGImage<PreInitializePageAndFrameForSVGImage,PrecompileInlineScripts<ThreadedBodyLoader,PreconnectToSearch<PreconnectToSearchDesktop,PreconnectToSearchWithPrivacyModeEnabled<PreconnectToSearchWithPrivacyModeEnabled,PrefetchDocumentManagerEarlyCookieCopySkipped<PrefetchDocumentManagerEarlyCookieCopySkipped,PrefetchProxy<PrefetchProxyDesktop,PrefetchReusable<PrefetchReusable,PrefetchUseContentRefactor<EagerPrefetchBlockUntilHeadDifferentTimeoutsRetrospective,PreloadMediaEngagementData<UnifiedAutoplay,PreloadSystemFonts<PreloadSystemFonts,PreloadTopChromeWebUI<PreloadTopChromeWebUI,PreloadingHeuristicsMLModel<PreloadingHeuristicsMLModel,Prerender2EarlyDocumentLifecycleUpdate<Prerender2EarlyDocumentLifecycleUpdate,Prerender2EmbedderBlockedHosts<Prerender2EmbedderBlockedHosts,Prerender2WarmUpCompositor<Prerender2WarmUpCompositor,PressAndHoldEscToExitBrowserFullscreen<PressAndHoldEscToExitBrowserFullscreen0612,PriceInsights<CommercePriceInsights,PriceTrackingIconColors<PriceTrackingIconColors,PrioritizeCompositingAfterDelayTrials<PrioritizeCompositingAfterDelay,PriorityHeader<PriorityHeader,PrivacySandboxAdsAPIsOverride,PrivacySandboxAttestationsLoadPreInstalledComponent<PrivacySandboxAttestationsLoadPreInstalledComponent,PrivacySandboxInternalsDevUI<PrivacySandboxInternalsDevUI,PrivacySandboxSettings4<PrivacySandboxV4,PrivateAggregationApiFilteringIds<PrivateAggregationApiFilteringIds,PrivateNetworkAccessRespectPreflightResults,PrivateStateTokens<PrivateStateTokens,ProcessHtmlDataImmediately<ProcessHtmlDataImmediately,ProcessReuseOnPrerenderCOOPSwap<ProcessReuseOnPrerenderCOOPSwap,ProfilesReordering<ProfilesReordering,PruneOldTransferCacheEntries<PruneOldTransferCacheEntries,PsRedesignAdPrivacyPage<PsRedesign,PushMessagingDisallowSenderIDs<PushMessagingDisallowSenderIDs,PushMessagingGcmEndpointEnvironment<PushMessagingGcmEndpointEnvironment,QuicDoesNotUseFeatures<QUIC,QuickIntensiveWakeUpThrottlingAfterLoading<CatanCombinedHoldback23H2,RTCAlignReceivedEncodedVideoTransforms<RTCAlignReceivedEncodedVideoTransforms,RasterInducingScroll<RasterInducingScroll,ReadAnythingDocsIntegration<ReadAnythingDocsIntegrationRollout,ReadAnythingLocalSidePanel<ReadAnythingLocalSidePanelRollout,ReadAnythingPermanentAccessibility<ReadAnythingPermanentAccessibility,RealTimeUrlFilteringCustomMessage<WebProtectCustomRuleMessageDialog,ReclaimOldPrepaintTiles<ReclaimOldPrepaintTiles,ReclaimPrepaintTilesWhenIdle<ReclaimPrepaintTilesWhenIdle,ReduceAcceptLanguage<ReduceAcceptLanguage,ReduceCookieIPCs<CatanCombinedHoldback23H2,ReduceCpuUtilization2<ReduceCpuUtilization2,ReduceIPAddressChangeNotification<ReduceIPAddressChangeNotification,ReduceTransferSizeUpdatedIPC<BackgroundResourceFetch,RegisterJSSourceLocationBlockingBFCache<BackForwardCacheCaptureBlockingDetails,RemotePageMetadata<RemotePageMetadataDesktopExpansion,RemoveDataUrlInSvgUse<RemoveDataUrlInSvgUse,RenderSizeInScoreAdBrowserSignals<ProtectedAudienceScoreAdRenderSize,ReportEventTimingAtVisibilityChange<ReportEventTimingAtVisibilityChange,ReportingServiceAlwaysFlush<ReportingServiceAlwaysFlush,ResourceAttributionIncludeOrigins<CPUMeasurementInFreezingPolicy,ResponsiveToolbar<SidePanelPinningWithResponsiveToolbar,RetryGetVideoCaptureDeviceInfos<RetryGetVideoCaptureDeviceInfos,RubyLineBreakable<RubyLineBreakable,RubyLineEdgeAlignment<RubyLineEdgeAlignment,RubyShortHeuristics<RubyShortHeuristics,RunPerformanceManagerOnMainThreadSync<RunPerformanceManagerOnMainThreadSync,RunTasksByBatches<CatanCombinedHoldback23H2,SafeBrowsingArchiveImprovements<SafeBrowsingNestedArchives,SafeBrowsingDeepScanningPromptRemoval<SafeBrowsingDeepScanningPromptRemoval,SafeBrowsingExtensionTelemetryDeclarativeNetRequestActionSignal<ExtensionTelemetryDeclarativeNetRequestActionSignal,SafeBrowsingSevenZipEvaluationEnabled<SafeBrowsingSevenZipEvaluationEnabled,SafeBrowsingStrictDownloadtimeout<SafeBrowsingNestedArchives,SafetyCheckUnusedSitePermissions<SafetyCheckUnusedSitePermissions,SafetyHub<SafetyHub,SafetyHubAbusiveNotificationRevocation<SafetyHubAbusiveNotificationRevocation,SafetyHubExtensionsNoPrivacyPracticesTrigger<ExtensionSafetyHubNoPrivacyPracticesTrigger,SavePasswordHashFromProfilePicker<SavePasswordHashFromProfilePicker,ScaleScrollbarAnimationTiming<ScaleScrollbarAnimationTiming,SchemefulSameSite,ScreenCaptureKitMacScreen<ScreenCaptureKitMacScreen,ScreenCaptureKitPickerScreen<DesktopCapturePermissionChecker,ScreenCaptureKitStreamPickerSonoma<DesktopCapturePermissionChecker,ScreenlockReauthPromoCard<ScreenlockReauthPromoCard,SearchNavigationPrefetch<SearchPrefetchHighPriorityPrefetches,SearchWebInSidePanel<SearchWebInSidePanel,SegmentationPlatformURLVisitResumptionRanker<DesktopNtpTabResumption,SegmentationPlatformUmaFromSqlDb<SegmentationPlatformUmaFromSqlDb,SerializeAccessibilityPostLifecycle<SerializeAccessibilityPostLifecycle,ServiceWorkerAutoPreload<ServiceWorkerAutoPreload,ServiceWorkerAvoidMainThreadForInitialization<ServiceWorkerAvoidMainThreadForInitialization,ServiceWorkerBypassFetchHandlerHashStrings<ServiceWorkerAutoPreload,ServiceWorkerClientIdAlignedWithSpec<PlzDedicatedWorker,ServiceWorkerDebugCorsExemptHeaderList<ServiceWorkerDebugCorsExemptHeaderList,ServiceWorkerFetchResponseCallbackUseHighPriority<FindRegistrationImprovements,ServiceWorkerMergeFindRegistrationForClientUrl<FindRegistrationImprovements,ServiceWorkerRegistrationCache<FindRegistrationImprovements,ServiceWorkerScopeCache<FindRegistrationImprovements,ServiceWorkerStaticRouter<ServiceWorkerStaticRouter,ServiceWorkerStorageControlOnThreadPool<FindRegistrationImprovements,ServiceWorkerStorageControlResponseUseHighPriority<FindRegistrationImprovements,ShareThisTabDialog<ShareThisTabDialog,SharedStorageAPI,SharedStorageAPIEnableWALForDatabase<PerfCombined2024,SharedWorkerBlobURLFix<SharedWorkerBlobURLFix,ShoppingList<PriceTrackingDesktopExpansionStudy,ShoppingPDPMetrics<EnablePDPMetricsUSDesktopIOS,ShowFeaturedEnterpriseSiteSearch<OmniboxFeaturedEnterpriseSiteSearch,ShowFeaturedEnterpriseSiteSearchIPH<OmniboxFeaturedEnterpriseSiteSearch,ShowSuggestionsOnAutofocus<ShowSuggestionsOnAutofocus,SidePanelCompanion<SidePanelCompanionDesktopM116Plus,SidePanelCompanionChromeOS<SidePanelCompanionDesktopM116Plus,SidePanelJourneys<SidePanelJourneys,SidePanelPinning<SidePanelPinningWithResponsiveToolbar,SimpleURLLoaderUseReadAndDiscardBodyOption<HttpDiskCachePrewarming,SimplifyLoadingTransparentPlaceholderImage<SimplifyLoadingTransparentPlaceholderImage,SingleVideoFrameRateThrottling<SingleVideoFrameRateThrottling,SkiaGraphite<SkiaGraphite,SkipConditionVariableWakeupHack<CatanCombinedHoldback23H2,SkipTpcdMitigationsForAds<CookieDeprecationFacilitatedTestingCookieDeprecation,SkipUnnecessaryThreadHopsForParseHeaders<SkipUnnecessaryThreadHopsForParseHeaders,SonomaAccessibilityActivationRefinements<SonomaAccessibilityActivationRefinements,SpdyHeadersToHttpResponseUseBuilder<SpdyHeadersToHttpResponseUseBuilder,SpeculativeServiceWorkerWarmUp<SpeculativeServiceWorkerWarmUp,SplitCacheByNetworkIsolationKey<SplitCacheByNetworkIsolationKey,SqlWALModeOnDipsDatabase<PerfCombined2024,SqlWALModeOnSegmentationDatabase<PerfCombined2024,StandardizedBrowserZoom<StandardizedBrowserZoom,StarterPackExpansion<DesktopOmniboxStarterPackExpansion,StarterPackIPH<OmniboxStarterPackIPH,StaticAnimationOptimization<OptimizeStaticAnimationProperties,StorageBuckets<StorageBuckets,StreamlineRendererInit<StreamlineRendererInit,SuppressesLoadingPredictorOnSlowNetwork<SuppressesNetworkActivitiesOnSlowNetwork,SuppressesPrerenderingOnSlowNetwork<SuppressesNetworkActivitiesOnSlowNetwork,SuppressesSearchPrefetchOnSlowNetwork<SuppressesNetworkActivitiesOnSlowNetwork,SyncAutofillWalletCredentialData<AutofillEnableCvcStorage,SyncAutofillWalletUsageData<AutofillEnableVirtualCardOnFile,SyncEnableContactInfoDataTypeForChildUsers<SyncEnableContactInfoDataTypeForChildUsers,SyncEnableContactInfoDataTypeInTransportMode<UnoDesktopM0Full,SyncIncreaseNudgeDelayForSingleClient<SyncIncreaseNudgeDelayForSingleClient,SyncPlusAddress<PlusAddressesExperiment,TPCDAdHeuristicSubframeRequestTagging<CookieDeprecationFacilitatedTestingCookieDeprecation,TabAudioMuting<TabAudioMuting,TabGroupsSaveUIUpdate<TabGroupsSaveUIUpdateAndSaveV2,TabGroupsSaveV2<TabGroupsSaveUIUpdateAndSaveV2,TabHoverCardImages<TabHoverCardImagesMacArm,TabOrganization<TabOrganization,TabOrganizationSettingsVisibility<ExperimentalFeaturesVisibilityDesktop,TabStripCollectionStorage<TabStripCollectionStorage,TailoredSecurityIntegration<TailoredSecurityIntegration,TextInputHostMojoCapabilityControlWorkaround<TextInputHostMojoCapabilityControlWorkaround,TextSafetyClassifier<ComposeOnDeviceModel,TextSizeAdjustImprovements<TextSizeAdjustImprovements,ThirdPartyScriptDetection<ThirdPartyScriptDetection,ThirdPartyStoragePartitioning,ThreadGroupSemaphore<ThreadGroupSemaphore,ThreadPoolCap2<ThreadPoolCap2,ThreadedScrollPreventRenderingStarvation<BlinkSchedulerCompositorTQPolicyDuringThreadedScroll,ThrottleUnimportantFrameTimers<ThrottleUnimportantFrameTimers,TimedHTMLParserBudget<TimedHTMLParserBudget,TimerSlackMac<BatterySaverModeAlignWakeUps,ToolbarPinning<ToolbarPinning,TopChromeWebUIUsesSpareRenderer<TopChromeWebUIUsesSpareRenderer,TrackingProtection3pcd<TrackingProtection3pcd,TransportSecurityFileWriterSchedule<TransportSecurityFileWriterSchedule,TrustSafetySentimentSurvey<TrustSafetySentimentSurvey,TrustSafetySentimentSurveyV2<TrustSafetySentimentSurveyV2,TrustTokens<TrustTokenOriginTrial,TurnOffStreamingMediaCachingAlways<TurnOffStreamingMediaCachingAlways,UIEnableSharedImageCacheForGpu<UIEnableSharedImageCacheForGpu,UMANonUniformityLogNormal<UMA-NonUniformity-Trial-1-Percent,UMAPseudoMetricsEffect<UMA-Pseudo-Metrics-Effect-Injection-25-Percent,UkmReduceAddEntryIPC<ReduceIPCCombined,UkmSamplingRate<UkmSamplingRate,UnblockTouchMoveEarlier<UnblockTouchMoveEarlier,UncredentialedFilteringFallbackForSupervisedUsers<KidsProfile,UrlScoringModel<OmniboxMlUrlPiecewiseMappedScoringDesktop,UseBoringSSLForRandBytes<UseBoringSSLForRandBytes,UseBuiltInMetalShaderCache<UseBuiltInMetalShaderCache,UseClientGmbInterface<UseClientGmbInterface,UseCompositorJob<CatanCombinedHoldback23H2,UseDnsHttpsSvcb<DnsHttpsSvcbTimeout,UseFamilyMemberRolePrefsForFeedback<FamilyMemberRoleFeedback,UseItemSnippetsAPI<UseItemSnippetsAPI,UseMoveNotCopyInAXTreeCombiner<UseMoveNotCopyInAXTreeCombiner,UseMoveNotCopyInMergeTreeUpdate<UseMoveNotCopyInMergeTreeUpdate,UseNewAlpsCodepointHttp2<ALPSNewCodepoint,UseNewAlpsCodepointQUIC<ALPSNewCodepoint,UseParkableImageSegmentReader<ParkableImages,UseRustJsonParser<RustyJSONParser,UseSmartRefForGPUFenceHandle<UseSmartRefForGPUFenceHandle,UseSnappyForParkableStrings<UseSnappyForParkableStrings,UseZstdForParkableStrings<ParkableStringExperiments,UserBypassUI<UserBypassUI,UserEducationExperienceVersion2<UserEducationV2Study,UsernameFirstFlowWithIntermediateValuesPredictions<UsernameFirstFlowWithIntermediateValuesPredictions,V8CppGCEnableLargerCage<V8CppGCEnableLargerCage,V8EfficiencyModeTiering<V8EfficiencyModeTiering,V8FlushBaselineCode<V8FlushBaselineCode,V8FlushCodeBasedOnTime<V8CodeFlushing,V8GCOptimizeSweepForMutator<V8GCOptimizeSweepForMutator,V8IntelJCCErratumMitigation<V8IntelJCCErratumMitigation,V8ScavengerHigherCapacity<V8ScavengerHigherCapacity,V8SideStepTransitions<V8SideStepTransitions,V8SingleThreadedGCInBackground<V8SingleThreadedGCInBackgroundVariants,V8UpdateLimitAfterLoading<V8UpdateLimitAfterLoading,VSyncAlignedPresent<VSyncAlignedPresent,VSyncDecoding<VSyncDecoding,VerifyDidCommitParams<VerifyDidCommitParams,ViewTransitionOnNavigation<ViewTransitionOnNavigation,VisibilityAwareResourceScheduler<VisibilityAwareResourceScheduler,VisitedURLRankingService<VisitedURLRankingService,VisualQuerySuggestions<SidePanelCompanionDesktopM116Plus,WaitForLateScrollEvents<WaitForLateScrollEvents,WallpaperSearchGraduated<ChromeWallpaperSearchGlobal,WarmUpCompositor<Prerender2WarmUpCompositor,WebAppUniversalInstall<DesktopWebAppUniversalInstallExperiment,WebAppsEnableMLModelForPromotion<DesktopPWAInstallPromotionML,WebAssemblyGenericWrapper<WebAssemblyGenericWrapper,WebAssemblyInliningCallIndirect<WebAssemblyInliningCallIndirect,WebAssemblyLiftoffCodeFlushing<V8WasmCodeFlushing,WebAssemblyMoreAggressiveCodeCaching<V8WasmMoreAggressiveCodeCaching,WebAssemblyTurboshaft<V8WasmTurboshaft,WebAssemblyTurboshaftInstructionSelection<V8WasmTurboshaft,WebAuthenticationEnclaveAuthenticator<WebAuthenticationEnclaveAuthenticator,WebContentsCaptureHiDPI<WebContentsCaptureHiDPI,WebGPUService<WebGPU,WebRTC-Video-H26xPacketBuffer<WebRTC-Video-H26xPacketBuffer,WebRTCHardwareVideoEncoderFrameDrop<WebRTCHardwareVideoEncoderFrameDrop,WebRtcEncodedTransformDirectCallback<WebRtcEncodedTransformDirectCallback,WebUIBubblePerProfilePersistence<WebUIBubblePersistentRendererStudy,WebUICodeCache<WebUICodeCache,WhatsNewVersion2<WhatsNewV2Study,ZeroCopyTabCapture<ZeroCopyTabCaptureStudyMac,ZeroSuggestPrefetchDebouncing<ZPSPrefetchDebouncingDesktop,kOmniboxCR23SteadyStateIcons<OmniboxCr23M113Desktop"',
    // '--disable-features="AVFoundationCaptureForwardSampleTimestamps<AVFoundationCaptureForwardSampleTimestamps,AcceptCHFrame,AutofillAddressSurvey<AutofillSurveys,AutofillPasswordSurvey<AutofillSurveys,CdmStorageDatabaseMigration<CdmStorageDatabaseDefaultTrial,ComposeEnableNudgeForUnspecifiedHint<ComposeEnableNudgeForUnspecifiedHint,ContextMenuSearchForVideoFrame<Chromnient,DOMParserIncludeShadowRoots<DOMParserIncludeShadowRoots,ElementGetInnerHTML<ElementGetInnerHTML,FingerprintingProtectionSetting<FingerprintingProtectionFilter,FingerprintingProtectionUx<FingerprintingProtectionFilter,HappinessTrackingSurveysForDesktopM1AdMeasurementSubpage<PrivacySandboxHatsForDesktopM1,HappinessTrackingSurveysForDesktopM1FledgeSubpage<PrivacySandboxHatsForDesktopM1,HappinessTrackingSurveysForDesktopM1TopicsSubpage<PrivacySandboxHatsForDesktopM1,HappinessTrackingSurveysForDesktopSettingsPrivacy<PrivacyGuideHats,IsolateSandboxedIframes,MediaRouter,MemoryCacheStrongReferenceFilterScripts<MemoryCacheStrongReference,MutationEvents<MutationEvents,NonStandardAppearanceValueSliderVertical<NonStandardAppearanceValueSliderVertical,NtpShoppingTasksModule<DesktopNtpModules,OptimizationHints,PartitionAllocSortActiveSlotSpans<PartitionAllocMemoryReclaimer,PerformanceControlsBatteryPerformanceSurvey<PerformanceControlsHatsStudy,PerformanceControlsBatterySaverOptOutSurvey<PerformanceControlsHatsStudy,PerformanceControlsPerformanceSurvey<PerformanceControlsHatsStudy,ProcessPerSiteUpToMainFrameThreshold,RecordSequenceManagerCrashKeys<CatanCombinedHoldback23H2,ReduceSubresourceResponseStartedIPC<ReduceIPCCombined,SideSearch<SidePanelCompanionDesktopM116Plus,SpeculativeServiceWorkerStartup<SpeculativeServiceWorkerWarmUp,TabGroupsCollapseFreezing<TabGroupsCollapseFreezing,TheoraVideoCodec<TheoraVideoCodec,ThreadControllerSetsProfilerMetadata<CatanCombinedHoldback23H2,ThreadedBodyLoader<ThreadedBodyLoader,ThreadedPreloadScanner<ThreadedBodyLoader,Translate,UrgentPageDiscarding<DisableUrgentPageDiscarding,UseGetrandomForRandBytes<UseBoringSSLForRandBytes,UseGles2ForOopR<DisableGles2ForOopR,V8FlushCodeBasedOnTabVisibility<V8CodeFlushing,V8SingleThreadedGCInBackgroundNoIncrementalMarking<V8SingleThreadedGCInBackgroundVariants,V8SingleThreadedGCInBackgroundParallelPause<V8SingleThreadedGCInBackgroundVariants,V8SlowHistograms<V8SlowHistograms,WallpaperSearchSettingsVisibility<ChromeWallpaperSearchGlobal"',
    '--disable-field-trial-config',
  ];
  const opts: puppeteer.LaunchOptions&puppeteer.BrowserLaunchArgumentOptions&puppeteer.BrowserConnectOptions = {
    headless,
    executablePath: TestConfig.chromeBinary,
    dumpio: !headless || Boolean(process.env['LUCI_CONTEXT']),
    slowMo: envSlowMo,
  };

  // Always set the default viewport because setting only the window size for
  // headful mode would result in much smaller actual viewport.
  opts.defaultViewport = {width: viewportWidth, height: viewportHeight};
  // Toggle either viewport or window size depending on headless vs not.
  if (!headless) {
    launchArgs.push(`--window-size=${windowWidth},${windowHeight}`);
  }

  if (envChromeFeatures) {
    enabledFeatures.push(envChromeFeatures);
  }
  launchArgs.push(`--enable-features=${enabledFeatures.join(',')}`);

  opts.args = launchArgs;
  return puppeteer.launch(opts);
}

async function loadTargetPageAndFrontend(testServerPort: number) {
  browser = await launchChrome();
  setupBrowserProcessIO(browser);

  // Load the target page.
  targetTab = await TargetTab.create(browser);

  // Create the frontend - the page that will be under test. This will be either
  // DevTools Frontend in hosted mode, or the component docs in docs test mode.
  let frontend: puppeteer.Page;

  if (TestConfig.serverType === 'hosted-mode') {
    /**
     * In hosted mode we run the DevTools and test against it.
     */
    frontendTab = await DevToolsFrontendTab.create({
      browser,
      testServerPort,
      targetId: targetTab.targetId(),
    });
    frontend = frontendTab.page;
  } else if (TestConfig.serverType === 'component-docs') {
    /**
     * In the component docs mode it points to the page where we load component
     * doc examples, so let's just set it to an empty page for now.
     */
    frontend = await browser.newPage();
    installPageErrorHandlers(frontend);
    await loadEmptyPageAndWaitForContent(frontend);
  } else {
    throw new Error(`Unknown TEST_SERVER_TYPE "${TestConfig.serverType}"`);
  }

  setBrowserAndPages({target: targetTab.page, frontend, browser});
}

export async function unregisterAllServiceWorkers() {
  const {target} = getBrowserAndPages();
  await target.evaluate(async () => {
    if (!navigator.serviceWorker) {
      return;
    }
    const registrations = await navigator.serviceWorker.getRegistrations();
    await Promise.all(registrations.map(r => r.unregister()));
  });
}

export async function resetPages(currentTest: string|undefined) {
  const {frontend, target} = getBrowserAndPages();

  await watchForHang(currentTest, () => target.bringToFront());
  await watchForHang(currentTest, () => targetTab.reset());

  await watchForHang(currentTest, () => frontend.bringToFront());
  await watchForHang(currentTest, () => throttleCPUIfRequired(frontend));
  await watchForHang(currentTest, () => delayPromisesIfRequired(frontend));

  if (TestConfig.serverType === 'hosted-mode') {
    await watchForHang(currentTest, () => frontendTab.reset());
  } else if (TestConfig.serverType === 'component-docs') {
    // Reset the frontend back to an empty page for the component docs server.
    await watchForHang(currentTest, () => loadEmptyPageAndWaitForContent(frontend));
  }
}

async function delayPromisesIfRequired(page: puppeteer.Page): Promise<void> {
  if (envLatePromises === 0) {
    return;
  }
  console.log(`Delaying promises by ${envLatePromises}ms`);
  await page.evaluate(delay => {
    globalThis.Promise = class<T> extends Promise<T>{
      constructor(executor: (resolve: (value: T|PromiseLike<T>) => void, reject: (reason?: unknown) => void) => void) {
        super((resolve, reject) => {
          executor(value => setTimeout(() => resolve(value), delay), reason => setTimeout(() => reject(reason), delay));
        });
      }
    };
  }, envLatePromises);
}

async function throttleCPUIfRequired(page: puppeteer.Page): Promise<void> {
  if (envThrottleRate === 1) {
    return;
  }
  console.log(`Throttling CPU: ${envThrottleRate}x slowdown`);
  const client = await page.target().createCDPSession();
  await client.send('Emulation.setCPUThrottlingRate', {
    rate: envThrottleRate,
  });
}

export async function reloadDevTools(options?: DevToolsFrontendReloadOptions) {
  await frontendTab.reload(options);
}

// Can be run multiple times in the same process.
export async function preFileSetup(serverPort: number) {
  setTestServerPort(serverPort);
  registerHandlers();
  await loadTargetPageAndFrontend(serverPort);
}

// Can be run multiple times in the same process.
export async function postFileTeardown() {
  // We need to kill the browser before we stop the hosted mode server.
  // That's because the browser could continue to make network requests,
  // even after we would have closed the server. If we did so, the requests
  // would fail and the test would crash on closedown. This only happens
  // for the very last test that runs.
  await browser.close();

  clearPuppeteerState();
  dumpCollectedErrors();
}

export function collectCoverageFromPage(): Promise<CoverageMapData|undefined> {
  const {frontend} = getBrowserAndPages();

  return frontend.evaluate('window.__coverage__') as Promise<CoverageMapData|undefined>;
}

export function getDevToolsFrontendHostname(): string {
  return frontendTab.hostname();
}
